// Comprehensive dataset of all 38 Districts of Tamil Nadu and their Main Areas & Agricultural Profiles
export interface MainArea {
  en: string;
  ta: string;
  type: 'Taluk' | 'Agri Hub' | 'Market Town' | 'Block';
  specialty?: string;
}

export interface AgriMandi {
  nameEn: string;
  nameTa: string;
  type: string;
  speciality: string;
}

export interface DistrictDetail {
  id: string;
  en: string;
  ta: string;
  capitalEn: string;
  capitalTa: string;
  zoneEn: string;
  zoneTa: string;
  coordinates: { lat: number; lng: number };
  mainAreas: MainArea[];
  majorCrops: { en: string; ta: string }[];
  soilTypes: { en: string; ta: string }[];
  annualRainfallMm: number;
  waterBasinEn: string;
  waterBasinTa: string;
  keyMandis: AgriMandi[];
  specialtyEn: string;
  specialtyTa: string;
  netCroppedAreaHa: number;
}

export const TN_38_DISTRICTS: DistrictDetail[] = [
  {
    id: 'ariyalur',
    en: 'Ariyalur',
    ta: 'அரியலூர்',
    capitalEn: 'Ariyalur',
    capitalTa: 'அரியலூர்',
    zoneEn: 'Cauvery Delta / North Eastern Zone',
    zoneTa: 'காவிரி டெல்டா / வடகிழக்கு மண்டலம்',
    coordinates: { lat: 11.1401, lng: 79.0786 },
    mainAreas: [
      { en: 'Ariyalur', ta: 'அரியலூர்', type: 'Taluk', specialty: 'Cotton & Sugarcane' },
      { en: 'Jayankondam', ta: 'ஜெயங்கொண்டம்', type: 'Taluk', specialty: 'Cashew (முந்திரி) processing hub' },
      { en: 'Udayarpalayam', ta: 'உடையார்பாளையம்', type: 'Taluk', specialty: 'Groundnut & Paddy' },
      { en: 'Sendurai', ta: 'செந்துறை', type: 'Taluk', specialty: 'Maize & Millets' },
      { en: 'Andimadam', ta: 'ஆண்டிமடம்', type: 'Taluk', specialty: 'Cashew plantations & Pulses' },
      { en: 'Thirumanur', ta: 'திருமானூர்', type: 'Agri Hub', specialty: 'Cauvery river irrigation belt' },
    ],
    majorCrops: [
      { en: 'Cashew', ta: 'முந்திரி' },
      { en: 'Cotton', ta: 'பருத்தி' },
      { en: 'Paddy', ta: 'நெல்' },
      { en: 'Sugarcane', ta: 'கரும்பு' },
      { en: 'Groundnut', ta: 'நிலக்கடலை' },
      { en: 'Maize', ta: 'மக்காச்சோளம்' },
    ],
    soilTypes: [
      { en: 'Red Loam', ta: 'செம்மண்' },
      { en: 'Clay Loam', ta: 'களிமண் வண்டல்' },
      { en: 'Black Soil', ta: 'கரிசல் மண்' },
    ],
    annualRainfallMm: 954,
    waterBasinEn: 'Coleroon (Kollidam) & Marudhaiyar River',
    waterBasinTa: 'கொள்ளிடம் & மருதையாறு பாசனம்',
    keyMandis: [
      { nameEn: 'Jayankondam Cashew Mandi', nameTa: 'ஜெயங்கொண்டம் முந்திரி மண்டி', type: 'Regulated Market', speciality: 'Raw & Processed Cashew' },
      { nameEn: 'Ariyalur Cotton Market', nameTa: 'அரியலூர் பருத்தி விற்பனைக் கூடம்', type: 'Regulated Market', speciality: 'Cotton & Maize' },
    ],
    specialtyEn: 'Famous for Jayankondam export-quality Cashews and fertile Coleroon riverbank soils.',
    specialtyTa: 'ஜெயங்கொண்டம் முந்திரி பதப்படுத்துதல் மற்றும் கொள்ளிடக் கரை வளமான நெல் விளைச்சல்.',
    netCroppedAreaHa: 112000,
  },
  {
    id: 'chengalpattu',
    en: 'Chengalpattu',
    ta: 'செங்கல்பட்டு',
    capitalEn: 'Chengalpattu',
    capitalTa: 'செங்கல்பட்டு',
    zoneEn: 'North Eastern Zone',
    zoneTa: 'வடகிழக்கு வேளாண் மண்டலம்',
    coordinates: { lat: 12.6841, lng: 79.9836 },
    mainAreas: [
      { en: 'Chengalpattu', ta: 'செங்கல்பட்டு', type: 'Taluk', specialty: 'Paddy & Vegetables' },
      { en: 'Maduranthakam', ta: 'மதுராந்தகம்', type: 'Taluk', specialty: 'Major Tank Irrigation & Paddy bowl' },
      { en: 'Cheyyur', ta: 'செய்யூர்', type: 'Taluk', specialty: 'Groundnut & Watermelon' },
      { en: 'Thirukalukundram', ta: 'திருக்கழுக்குன்றம்', type: 'Taluk', specialty: 'Paddy & Banana' },
      { en: 'Tiruporur', ta: 'திருப்போரூர்', type: 'Taluk', specialty: 'Horticulture & Greenhouses' },
      { en: 'Vandalur', ta: 'வண்டலூர்', type: 'Agri Hub', specialty: 'Floriculture & Nurseries' },
    ],
    majorCrops: [
      { en: 'Paddy', ta: 'நெல்' },
      { en: 'Groundnut', ta: 'நிலக்கடலை' },
      { en: 'Watermelon', ta: 'தர்பூசணி' },
      { en: 'Sugarcane', ta: 'கரும்பு' },
      { en: 'Pulses', ta: 'பயறு வகைகள்' },
    ],
    soilTypes: [
      { en: 'Sandy Clay Loam', ta: 'மணல் கலந்த களிமண்' },
      { en: 'Red Sandy Loam', ta: 'செம்மண்' },
      { en: 'Coastal Alluvium', ta: 'கடற்கரை வண்டல்' },
    ],
    annualRainfallMm: 1210,
    waterBasinEn: 'Palar River Basin & Maduranthakam Big Lake',
    waterBasinTa: 'பாலாறு பாசனம் & மதுராந்தகம் ஏரி',
    keyMandis: [
      { nameEn: 'Maduranthakam Regulated Market', nameTa: 'மதுராந்தகம் ஒழுங்குமுறை விற்பனைக்கூடம்', type: 'Regulated Market', speciality: 'Paddy & Pulses' },
      { nameEn: 'Chengalpattu Uzhavar Sandhai', nameTa: 'செங்கல்பட்டு உழவர் சந்தை', type: 'Uzhavar Sandhai', speciality: 'Fresh Vegetables & Greens' },
    ],
    specialtyEn: 'Maduranthakam Eri second largest irrigation lake in TN, prime watermelon and paddy center.',
    specialtyTa: 'மதுராந்தகம் ஏரி பாசனம், கோடை தர்பூசணி மற்றும் தரமான நெல் சாகுபடி மையம்.',
    netCroppedAreaHa: 104000,
  },
  {
    id: 'chennai',
    en: 'Chennai',
    ta: 'சென்னை',
    capitalEn: 'Chennai',
    capitalTa: 'சென்னை',
    zoneEn: 'Coastal Agri Commercial Terminal',
    zoneTa: 'கடலோர வேளாண் சந்தை முனையம்',
    coordinates: { lat: 13.0827, lng: 80.2707 },
    mainAreas: [
      { en: 'Koyambedu', ta: 'கோயம்பேடு', type: 'Agri Hub', specialty: 'Asia’s Largest Agri Perishable Wholesale Terminal' },
      { en: 'Madhavaram', ta: 'மாதவரம்', type: 'Taluk', specialty: 'Dairy & Horticulture Research' },
      { en: 'Tondiarpet', ta: 'தண்டையார்பேட்டை', type: 'Taluk', specialty: 'Marine Fisheries Trade' },
      { en: 'Mylapore', ta: 'மயிலாப்பூர்', type: 'Agri Hub', specialty: 'Urban Organic Farming & Terrace Gardens' },
      { en: 'Guindy', ta: 'கிண்டி', type: 'Agri Hub', specialty: 'Agri Tech & TNAU Information Center' },
    ],
    majorCrops: [
      { en: 'Terrace & Microgreens', ta: 'மாடித்தோட்டம் & கீரைகள்' },
      { en: 'Nursery Plants', ta: 'நாற்றுப் பண்ணை மரங்கள்' },
      { en: 'Horticulture Flowers', ta: 'மலர்கள்' },
    ],
    soilTypes: [
      { en: 'Coastal Alluvial', ta: 'கடற்கரை வண்டல்' },
      { en: 'Sandy Soil', ta: 'மணல் மண்' },
    ],
    annualRainfallMm: 1380,
    waterBasinEn: 'Cooum & Adyar Estuaries',
    waterBasinTa: 'கூவம் & அடையாறு பாசனாப் பகுதி',
    keyMandis: [
      { nameEn: 'Koyambedu Perishable Wholesale Market', nameTa: 'கோயம்பேடு மொத்த காய்கறி & பழ அங்காடி', type: 'Wholesale Terminal', speciality: 'Vegetables, Fruits & Flowers' },
    ],
    specialtyEn: 'Central consumption hub and benchmark pricing anchor for all South Indian agriculture produce.',
    specialtyTa: 'தென்னிந்திய வேளாண் விளைபொருட்களின் முதன்மை விலை நிர்ணய மற்றும் நுகர்வு மையம்.',
    netCroppedAreaHa: 1800,
  },
  {
    id: 'coimbatore',
    en: 'Coimbatore',
    ta: 'கோயம்புத்தூர்',
    capitalEn: 'Coimbatore',
    capitalTa: 'கோயம்புத்தூர்',
    zoneEn: 'Western Agro-Climatic Zone',
    zoneTa: 'மேற்கு வேளாண் மண்டலம்',
    coordinates: { lat: 11.0168, lng: 76.9558 },
    mainAreas: [
      { en: 'Pollachi', ta: 'பொள்ளாச்சி', type: 'Taluk', specialty: 'Coconut Capital of India & Tender Coconut Hub' },
      { en: 'Mettupalayam', ta: 'மேட்டுப்பாளையம்', type: 'Taluk', specialty: 'Bhavani Basin Banana & Hill Potato Mandi' },
      { en: 'Sulur', ta: 'சூலூர்', type: 'Taluk', specialty: 'Cotton, Maize & Poultry' },
      { en: 'Annur', ta: 'அன்னூர்', type: 'Taluk', specialty: 'Millets, Sorghum & Vegetables' },
      { en: 'Kinathukadavu', ta: 'கிணத்துக்கடவு', type: 'Taluk', specialty: 'Tomato & Coconut Farms' },
      { en: 'Valparai', ta: 'வால்பாறை', type: 'Taluk', specialty: 'High Altitude Tea & Coffee' },
      { en: 'Madukkarai', ta: 'மதுக்கரை', type: 'Taluk', specialty: 'Dairy & Fodder crops' },
    ],
    majorCrops: [
      { en: 'Coconut', ta: 'தென்னை' },
      { en: 'Cotton', ta: 'பருத்தி' },
      { en: 'Tea', ta: 'தேயிலை' },
      { en: 'Maize', ta: 'மக்காச்சோளம்' },
      { en: 'Tomato & Vegetables', ta: 'தக்காளி & காய்கறிகள்' },
      { en: 'Banana', ta: 'வாழை' },
    ],
    soilTypes: [
      { en: 'Black Cotton Soil', ta: 'கரிசல் மண்' },
      { en: 'Red Gravelly Loam', ta: 'செம்மண் சரளை' },
      { en: 'Hill Laterite', ta: 'மலைச் சரளை மண்' },
    ],
    annualRainfallMm: 698,
    waterBasinEn: 'Parambikulam Aliyar Project (PAP) & Noyyal River',
    waterBasinTa: 'பரம்பிக்குளம் ஆழியாறு திட்டம் (PAP) & நொய்யல்',
    keyMandis: [
      { nameEn: 'Pollachi Coconut Wholesale Mandi', nameTa: 'பொள்ளாச்சி தென்னை & இளநீர் மண்டி', type: 'National Mandi', speciality: 'Tender & Copra Coconut' },
      { nameEn: 'Mettupalayam Nilgiris Potato Market', nameTa: 'மேட்டுப்பாளையம் உருளைக்கிழங்கு மண்டி', type: 'Wholesale Market', speciality: 'Hill Vegetables' },
    ],
    specialtyEn: 'Headquarters of Tamil Nadu Agricultural University (TNAU) and world-renowned Pollachi coconut agro-belt.',
    specialtyTa: 'தமிழ்நாடு வேளாண்மைப் பல்கலைக்கழகம் (TNAU) மற்றும் பொள்ளாச்சி இளநீர் & தேங்காய் தலைநகரம்.',
    netCroppedAreaHa: 174000,
  },
  {
    id: 'cuddalore',
    en: 'Cuddalore',
    ta: 'கடலூர்',
    capitalEn: 'Cuddalore',
    capitalTa: 'கடலூர்',
    zoneEn: 'Cauvery Delta & Coastal Zone',
    zoneTa: 'காவிரி டெல்டா & கடற்கரை மண்டலம்',
    coordinates: { lat: 11.7480, lng: 79.7714 },
    mainAreas: [
      { en: 'Panruti', ta: 'பண்ருட்டி', type: 'Taluk', specialty: 'GI Tag Panruti Jackfruit (பலா) & Cashew belt' },
      { en: 'Chidambaram', ta: 'சிதம்பரம்', type: 'Taluk', specialty: 'Coleroon river paddy & freshwater aquaculture' },
      { en: 'Virudhachalam', ta: 'விருத்தாசலம்', type: 'Taluk', specialty: 'Groundnut, Sesame & Cashew Research Station' },
      { en: 'Kattumannarkoil', ta: 'காட்டுமன்னார்கோயில்', type: 'Taluk', specialty: 'Veeranam Lake ayacut paddy' },
      { en: 'Bhuvanagiri', ta: 'புவனகிரி', type: 'Taluk', specialty: 'Sugarcane & Rice' },
      { en: 'Kurinjipadi', ta: 'குறிஞ்சிப்பாடி', type: 'Taluk', specialty: 'Handloom & Millets' },
      { en: 'Tittagudi', ta: 'திட்டக்குடி', type: 'Taluk', specialty: 'Maize & Cotton' },
    ],
    majorCrops: [
      { en: 'Jackfruit', ta: 'பலாப்பழம் (பண்ருட்டி GI)' },
      { en: 'Cashew', ta: 'முந்திரி' },
      { en: 'Paddy', ta: 'நெல்' },
      { en: 'Sugarcane', ta: 'கரும்பு' },
      { en: 'Groundnut', ta: 'நிலக்கடலை' },
    ],
    soilTypes: [
      { en: 'Coastal Alluvial', ta: 'கடற்கரை வண்டல் மண்' },
      { en: 'Red Sandy Loam', ta: 'செம்மண்' },
      { en: 'Clay Loam', ta: 'களிமண் வண்டல்' },
    ],
    annualRainfallMm: 1240,
    waterBasinEn: 'Veeranam Lake, Vellar & Coleroon River',
    waterBasinTa: 'வீராணம் ஏரி, வெள்ளாறு & கொள்ளிடம்',
    keyMandis: [
      { nameEn: 'Panruti Jackfruit & Cashew Market', nameTa: 'பண்ருட்டி பலா & முந்திரி சந்தை', type: 'Specialized Mandi', speciality: 'Jackfruit & Cashew' },
      { nameEn: 'Virudhachalam Regulated Market', nameTa: 'விருத்தாசலம் ஒழுங்குமுறை விற்பனைக்கூடம்', type: 'Regulated Market', speciality: 'Groundnut & Sesame' },
    ],
    specialtyEn: 'Panruti GI Jackfruit and vast historical Veeranam Lake irrigation feeding thousands of acres.',
    specialtyTa: 'பண்ருட்டி பலாப்பழம், முந்திரி மற்றும் பிரசித்தி பெற்ற வீராணம் ஏரி பாசனப் பரப்புகள்.',
    netCroppedAreaHa: 215000,
  },
  {
    id: 'dharmapuri',
    en: 'Dharmapuri',
    ta: 'தருமபுரி',
    capitalEn: 'Dharmapuri',
    capitalTa: 'தருமபுரி',
    zoneEn: 'North Western Zone',
    zoneTa: 'வடமேற்கு வேளாண் மண்டலம்',
    coordinates: { lat: 12.1211, lng: 78.1582 },
    mainAreas: [
      { en: 'Palacode', ta: 'பாலக்கோடு', type: 'Taluk', specialty: 'State’s largest Tomato (தக்காளி) market' },
      { en: 'Harur', ta: 'அரூர்', type: 'Taluk', specialty: 'Sugarcane, Tapioca & Millets' },
      { en: 'Pennagaram', ta: 'பெண்ணாகரம்', type: 'Taluk', specialty: 'Hogenakkal belt, Ragi & Sesame' },
      { en: 'Pappireddipatti', ta: 'பாப்பிரெட்டிப்பட்டி', type: 'Taluk', specialty: 'Turmeric, Mango & Coffee in Shevaroy foothills' },
      { en: 'Karimangalam', ta: 'காரிமங்கலம்', type: 'Taluk', specialty: 'Mango orchards & Mulberry sericulture' },
      { en: 'Nallampalli', ta: 'நல்லம்பள்ளி', type: 'Taluk', specialty: 'Vegetables & Floriculture' },
    ],
    majorCrops: [
      { en: 'Tomato', ta: 'தக்காளி' },
      { en: 'Mango', ta: 'மாம்பழம்' },
      { en: 'Ragi (Finger Millet)', ta: 'கேழ்வரகு' },
      { en: 'Sugarcane', ta: 'கரும்பு' },
      { en: 'Turmeric', ta: 'மஞ்சள்' },
      { en: 'Mulberry (Silk)', ta: 'பட்டுப்புழு மல்பெரி' },
    ],
    soilTypes: [
      { en: 'Red Sandy Loam', ta: 'செம்மண்' },
      { en: 'Gravelly Clay Loam', ta: 'சரளைக் களிமண்' },
    ],
    annualRainfallMm: 853,
    waterBasinEn: 'Cauvery & Chinnar River Basin',
    waterBasinTa: 'காவிரி & சின்னாறு பாசனம்',
    keyMandis: [
      { nameEn: 'Palacode Daily Tomato Mandi', nameTa: 'பாலக்கோடு தினசரி தக்காளி சந்தை', type: 'Veg Terminal', speciality: 'Tomato & Capsicum' },
      { nameEn: 'Dharmapuri Mango Regulated Market', nameTa: 'தருமபுரி மாம்பழ ஒழுங்குமுறை விற்பனைக்கூடம்', type: 'Fruit Mandi', speciality: 'Bangalora & Alphonso Mango' },
    ],
    specialtyEn: 'Prime tomato production epicenter of Tamil Nadu and high-yield millets & sericulture belt.',
    specialtyTa: 'தமிழகத்தின் முதன்மை தக்காளி உற்பத்தி மையம், சிறுதானியங்கள் மற்றும் பட்டுப்புழு வளர்ப்பு.',
    netCroppedAreaHa: 168000,
  },
  {
    id: 'dindigul',
    en: 'Dindigul',
    ta: 'திண்டுக்கல்',
    capitalEn: 'Dindigul',
    capitalTa: 'திண்டுக்கல்',
    zoneEn: 'Southern Agro Zone & Hill Microclimate',
    zoneTa: 'தென் மண்டலம் & மலைப்பகுதி',
    coordinates: { lat: 10.3673, lng: 77.9803 },
    mainAreas: [
      { en: 'Oddanchatram', ta: 'ஒட்டன்சத்திரம்', type: 'Taluk', specialty: 'Asia’s major daily vegetable export wholesale hub' },
      { en: 'Nilakottai', ta: 'நிலக்கோட்டை', type: 'Taluk', specialty: 'Jasmine, Kanakambaram & flower market' },
      { en: 'Palani', ta: 'பழனி', type: 'Taluk', specialty: 'Paddy, Sugarcane & Panchamirtham ingredients' },
      { en: 'Kodaikanal', ta: 'கொடைக்கானல்', type: 'Taluk', specialty: 'Kodaikanal Hill Garlic (GI), Plums, Pears, Carrot' },
      { en: 'Natham', ta: 'நத்தம்', type: 'Taluk', specialty: 'Mango orchards & Coconut' },
      { en: 'Athoor', ta: 'ஆத்தூர்', type: 'Taluk', specialty: 'Kamarajar Sagar dam ayacut & Banana' },
      { en: 'Vedasandur', ta: 'வேடசந்தூர்', type: 'Taluk', specialty: 'Tobacco Research & Drumstick' },
      { en: 'Gujiliamparai', ta: 'குஜிலியம்பாறை', type: 'Taluk', specialty: 'Millets & Cotton' },
    ],
    majorCrops: [
      { en: 'Vegetables (Oddanchatram)', ta: 'காய்கறிகள்' },
      { en: 'Hill Garlic (GI)', ta: 'கொடைக்கானல் மலைப்பூண்டு (GI)' },
      { en: 'Flowers / Jasmine', ta: 'பூக்கள் & மல்லிகை' },
      { en: 'Maize', ta: 'மக்காச்சோளம்' },
      { en: 'Sirumalai Banana', ta: 'சிறுமலை வாழை' },
      { en: 'Drumstick (Moringa)', ta: 'முருங்கை' },
    ],
    soilTypes: [
      { en: 'Red Loam', ta: 'செம்மண்' },
      { en: 'Black Cotton', ta: 'கரிசல் மண்' },
      { en: 'Hill Forest Soil', ta: 'மலைக் காடு மண்' },
    ],
    annualRainfallMm: 812,
    waterBasinEn: 'Shanmuganadhi, Amaravathi & Vaigai Basins',
    waterBasinTa: 'சண்முகநதி, அமராவதி & வைகை பாசனம்',
    keyMandis: [
      { nameEn: 'Oddanchatram Gandhi Vegetable Market', nameTa: 'ஒட்டன்சத்திரம் காந்தி காய்கறி சந்தை', type: 'Interstate Hub', speciality: 'Vegetables (1000+ tons/day)' },
      { nameEn: 'Nilakottai Flower Market', nameTa: 'நிலக்கோட்டை பூக்கள் சந்தை', type: 'Flower Mandi', speciality: 'Jasmine & Crossandra' },
    ],
    specialtyEn: 'Oddanchatram vegetable market feeding Kerala and TN daily; GI tagged Kodaikanal Hill Garlic.',
    specialtyTa: 'தினசரி 1000+ டன் காய்கறி கையாளும் ஒட்டன்சத்திரம் சந்தை & GI பெற்ற கொடைக்கானல் மலைப்பூண்டு.',
    netCroppedAreaHa: 198000,
  },
  {
    id: 'erode',
    en: 'Erode',
    ta: 'ஈரோடு',
    capitalEn: 'Erode',
    capitalTa: 'ஈரோடு',
    zoneEn: 'Western Agro-Climatic Zone',
    zoneTa: 'மேற்கு வேளாண் மண்டலம்',
    coordinates: { lat: 11.3410, lng: 77.7172 },
    mainAreas: [
      { en: 'Erode', ta: 'ஈரோடு', type: 'Taluk', specialty: 'GI Tag Erode Turmeric (மஞ்சள் மாநகரம்)' },
      { en: 'Bhavani', ta: 'பவானி', type: 'Taluk', specialty: 'Kooduthurai confluence, Sugarcane & Paddy' },
      { en: 'Gobichettipalayam', ta: 'கோபிசெட்டிபாளையம்', type: 'Taluk', specialty: 'Paddy, Banana & Pioneer in Drip Irrigation' },
      { en: 'Sathyamangalam', ta: 'சத்தியமங்கலம்', type: 'Taluk', specialty: 'Bhavanisagar Dam ayacut & Flower auction' },
      { en: 'Anthiyur', ta: 'அந்தியூர்', type: 'Taluk', specialty: 'Cattle & Agri Fair, Tapioca & Groundnut' },
      { en: 'Perundurai', ta: 'பெருந்துறை', type: 'Taluk', specialty: 'Tapioca & Copra processing' },
      { en: 'Kodumudi', ta: 'கொடுமுடி', type: 'Taluk', specialty: 'Cauvery bank Banana & Betel vine' },
      { en: 'Thalavadi', ta: 'தாளவாடி', type: 'Taluk', specialty: 'Hill vegetables, Ragi, Potato & Garlic' },
    ],
    majorCrops: [
      { en: 'Turmeric (Erode GI)', ta: 'ஈரோடு மஞ்சள் (GI)' },
      { en: 'Sugarcane', ta: 'கரும்பு' },
      { en: 'Paddy', ta: 'நெல்' },
      { en: 'Banana', ta: 'வாழை' },
      { en: 'Tapioca', ta: 'மரவள்ளிக்கிழங்கு' },
      { en: 'Coconut', ta: 'தென்னை' },
    ],
    soilTypes: [
      { en: 'Alluvial Loam', ta: 'வண்டல் மண்' },
      { en: 'Red Loam', ta: 'செம்மண்' },
      { en: 'Black Loam', ta: 'கரிசல் மண்' },
    ],
    annualRainfallMm: 710,
    waterBasinEn: 'Bhavani, Cauvery, Noyyal & Kalingarayan Canal',
    waterBasinTa: 'பவானி, காவிரி & காளிங்கராயன் வாய்க்கால்',
    keyMandis: [
      { nameEn: 'Erode Turmeric Regulated Market (Semmampalayam)', nameTa: 'ஈரோடு மஞ்சள் ஒழுங்குமுறை விற்பனைக்கூடம்', type: 'National Mandi', speciality: 'Finger & Bulb Turmeric' },
      { nameEn: 'Sathyamangalam Flower Market', nameTa: 'சத்தியமங்கலம் பூக்கள் சந்தை', type: 'Flower Mandi', speciality: 'Mullai, Malli, Sevanthi' },
    ],
    specialtyEn: 'The Turmeric City of India with iconic 700-year-old Kalingarayan Canal sustainable irrigation.',
    specialtyTa: 'இந்தியாவின் மஞ்சள் மாநகரம் மற்றும் 700 ஆண்டுகள் பழமையான காளிங்கராயன் பாசன வரலாற்று சிறப்பு.',
    netCroppedAreaHa: 182000,
  },
  {
    id: 'kallakurichi',
    en: 'Kallakurichi',
    ta: 'கள்ளக்குறிச்சி',
    capitalEn: 'Kallakurichi',
    capitalTa: 'கள்ளக்குறிச்சி',
    zoneEn: 'North Eastern / Central Zone',
    zoneTa: 'வடகிழக்கு / மத்திய மண்டலம்',
    coordinates: { lat: 11.7383, lng: 78.9639 },
    mainAreas: [
      { en: 'Kallakurichi', ta: 'கள்ளக்குறிச்சி', type: 'Taluk', specialty: 'Sugarcane & Rice mills cluster' },
      { en: 'Chinnasalem', ta: 'சின்னசேலம்', type: 'Taluk', specialty: 'Modern Rice Mills & Paddy procurement' },
      { en: 'Sankarapuram', ta: 'சங்கராபுரம்', type: 'Taluk', specialty: 'Paddy, Maize & Groundnut' },
      { en: 'Tirukoilur', ta: 'திருக்கோவிலூர்', type: 'Taluk', specialty: 'Thenpennai riverbank Paddy & Pulses' },
      { en: 'Ulundurpet', ta: 'உளுந்தூர்பேட்டை', type: 'Taluk', specialty: 'Blackgram (உளுந்து) & Cashew' },
      { en: 'Kalvarayan Hills', ta: 'கல்வராயன் மலை', type: 'Taluk', specialty: 'Organic Millets, Pepper & Forest Honey' },
    ],
    majorCrops: [
      { en: 'Sugarcane', ta: 'கரும்பு' },
      { en: 'Paddy', ta: 'நெல்' },
      { en: 'Maize', ta: 'மக்காச்சோளம்' },
      { en: 'Blackgram', ta: 'உளுந்து' },
      { en: 'Tapioca', ta: 'மரவள்ளிக்கிழங்கு' },
      { en: 'Millets', ta: 'சிறுதானியங்கள்' },
    ],
    soilTypes: [
      { en: 'Red Sandy Loam', ta: 'செம்மண்' },
      { en: 'Clay Loam', ta: 'களிமண் வண்டல்' },
      { en: 'Gravelly Hill Soil', ta: 'மலை மண்' },
    ],
    annualRainfallMm: 1020,
    waterBasinEn: 'Thenpennai & Manimuktha River, Gomukhi Dam',
    waterBasinTa: 'தென்பெண்ணை & மணிமுக்தா, கோமுகி அணை',
    keyMandis: [
      { nameEn: 'Chinnasalem Modern Rice Mills Hub', nameTa: 'சின்னசேலம் நவீன அரிசி ஆலைகள் மண்டி', type: 'Rice Terminal', speciality: 'Paddy & Boiled Rice' },
      { nameEn: 'Kallakurichi Regulated Market', nameTa: 'கள்ளக்குறிச்சி ஒழுங்குமுறை விற்பனைக்கூடம்', type: 'Regulated Market', speciality: 'Sugarcane Jaggery & Maize' },
    ],
    specialtyEn: 'Massive rice-milling hub in Chinnasalem, major sugarcane production, and tribal organic farming.',
    specialtyTa: 'சின்னசேலம் நவீன அரிசி ஆலைகள், சர்க்கரை ஆலை கரும்பு சாகுபடி மற்றும் கல்வராயன் மலை இயற்கை வேளாண்மை.',
    netCroppedAreaHa: 195000,
  },
  {
    id: 'kanchipuram',
    en: 'Kanchipuram',
    ta: 'காஞ்சிபுரம்',
    capitalEn: 'Kanchipuram',
    capitalTa: 'காஞ்சிபுரம்',
    zoneEn: 'North Eastern Zone',
    zoneTa: 'வடகிழக்கு வேளாண் மண்டலம்',
    coordinates: { lat: 12.8342, lng: 79.7036 },
    mainAreas: [
      { en: 'Kanchipuram', ta: 'காஞ்சிபுரம்', type: 'Taluk', specialty: 'Paddy & Traditional Varieties' },
      { en: 'Sriperumbudur', ta: 'ஸ்ரீபெரும்புதூர்', type: 'Taluk', specialty: 'Vegetables, Floriculture & Peri-urban dairy' },
      { en: 'Walajabad', ta: 'வாலாஜாபாத்', type: 'Taluk', specialty: 'Paddy, Groundnut & Sugarcane' },
      { en: 'Uthiramerur', ta: 'உத்திரமேரூர்', type: 'Taluk', specialty: 'Historic tank irrigation, Paddy & Watermelon' },
      { en: 'Kundrathur', ta: 'குன்றத்தூர்', type: 'Taluk', specialty: 'Vegetables & Green Leafy Greens' },
    ],
    majorCrops: [
      { en: 'Paddy', ta: 'நெல்' },
      { en: 'Groundnut', ta: 'நிலக்கடலை' },
      { en: 'Sugarcane', ta: 'கரும்பு' },
      { en: 'Watermelon', ta: 'தர்பூசணி' },
      { en: 'Green Vegetables', ta: 'கீரைகள் & காய்கறிகள்' },
    ],
    soilTypes: [
      { en: 'Red Sandy Loam', ta: 'செம்மண்' },
      { en: 'Clayey Alluvium', ta: 'களிமண் வண்டல்' },
    ],
    annualRainfallMm: 1190,
    waterBasinEn: 'Palar & Cheyyar River, Uthiramerur Big Tank',
    waterBasinTa: 'பாலாறு & செய்யாறு, உத்திரமேரூர் பெரிய ஏரி',
    keyMandis: [
      { nameEn: 'Kanchipuram Regulated Market', nameTa: 'காஞ்சிபுரம் ஒழுங்குமுறை விற்பனைக்கூடம்', type: 'Regulated Market', speciality: 'Paddy & Groundnut' },
      { nameEn: 'Uthiramerur Agri Market', nameTa: 'உத்திரமேரூர் வேளாண் சந்தை', type: 'Local Mandi', speciality: 'Pulses & Paddy' },
    ],
    specialtyEn: 'Historic city of thousands of irrigation tanks with rich agricultural traditions recorded in stone inscriptions.',
    specialtyTa: 'ஆயிரக்கணக்கான வரலாற்றுச் சிறப்புமிக்க பாசன ஏரிகள் மற்றும் உத்திரமேரூர் பழங்கால வேளாண் நிர்வாக முறை.',
    netCroppedAreaHa: 98000,
  },
  {
    id: 'kanyakumari',
    en: 'Kanyakumari',
    ta: 'கன்னியாகுமரி',
    capitalEn: 'Nagercoil',
    capitalTa: 'நாகர்கோவில்',
    zoneEn: 'High Rainfall Southern Zone',
    zoneTa: 'அதிக மழைபெறும் தென் மண்டலம்',
    coordinates: { lat: 8.0883, lng: 77.5385 },
    mainAreas: [
      { en: 'Nagercoil', ta: 'நாகர்கோவில்', type: 'Taluk', specialty: 'Vadasery Banana Market & Paddy' },
      { en: 'Thovalai', ta: 'தோவாளை', type: 'Taluk', specialty: 'Flower capital of South India (பிச்சி, மல்லி)' },
      { en: 'Agastheeswaram', ta: 'அகஸ்தீஸ்வரம்', type: 'Taluk', specialty: 'Paddy & Coconut groves' },
      { en: 'Kalkulam', ta: 'கல்குளம்', type: 'Taluk', specialty: 'Rubber plantations & Tapioca' },
      { en: 'Vilavancode', ta: 'விளவங்கோடு', type: 'Taluk', specialty: 'Rubber, Spices (Clove, Pepper) & Banana' },
      { en: 'Killiyoor', ta: 'கிள்ளியூர்', type: 'Taluk', specialty: 'Coastal Coconut & Fisheries' },
      { en: 'Thiruvattar', ta: 'திருவட்டார்', type: 'Taluk', specialty: 'Kodayar river basin Honey & Spices' },
    ],
    majorCrops: [
      { en: 'Rubber', ta: 'ரப்பர்' },
      { en: 'Coconut', ta: 'தென்னை' },
      { en: 'Matti Banana (GI)', ta: 'மட்டி வாழை (GI)' },
      { en: 'Paddy', ta: 'நெல்' },
      { en: 'Cloves & Pepper', ta: 'கிராம்பு & மிளகு' },
      { en: 'Thovalai Flowers', ta: 'தோவாளை மலர்கள்' },
    ],
    soilTypes: [
      { en: 'Laterite Soil', ta: 'சரளை மண்' },
      { en: 'Deep Red Loam', ta: 'ஆழ்ந்த செம்மண்' },
      { en: 'Coastal Alluvium', ta: 'கடற்கரை வண்டல்' },
    ],
    annualRainfallMm: 1465,
    waterBasinEn: 'Pechiparai, Perunchani Dam & Kodayar River',
    waterBasinTa: 'பேச்சிப்பாறை, பெருஞ்சாணி அணை & கோதையாறு',
    keyMandis: [
      { nameEn: 'Thovalai Flower Wholesale Market', nameTa: 'தோவாளை பூக்கள் மொத்த அங்காடி', type: 'Flower Terminal', speciality: 'Jasmine, Pichipoo, Sevvanthi' },
      { nameEn: 'Kulasekharam Rubber Mandi', nameTa: 'குலசேகரம் ரப்பர் சந்தை', type: 'Commodity Mandi', speciality: 'Natural Rubber Sheets' },
    ],
    specialtyEn: 'Highest rainfall in Tamil Nadu, GI-certified Matti Banana, and Thovalai flower exports.',
    specialtyTa: 'தமிழகத்தின் அதிக மழைபெறும் மாவட்டம், GI அங்கீகாரம் பெற்ற மட்டி வாழை மற்றும் தோவாளை பூச்சந்தை.',
    netCroppedAreaHa: 76000,
  },
  {
    id: 'karur',
    en: 'Karur',
    ta: 'கரூர்',
    capitalEn: 'Karur',
    capitalTa: 'கரூர்',
    zoneEn: 'Cauvery Central Basin / Southern Zone',
    zoneTa: 'காவிரி மத்திய படுகை மண்டலம்',
    coordinates: { lat: 10.9601, lng: 78.0766 },
    mainAreas: [
      { en: 'Aravakurichi', ta: 'அரவக்குறிச்சி', type: 'Taluk', specialty: 'Drumstick (முருங்கை) Capital of South India' },
      { en: 'Kulithalai', ta: 'குளித்தலை', type: 'Taluk', specialty: 'Cauvery riverbank Banana & Paddy' },
      { en: 'Krishnarayapuram', ta: 'கிருஷ்ணராயபுரம்', type: 'Taluk', specialty: 'Sugarcane, Banana & Betel vine' },
      { en: 'Manmangalam', ta: 'மண்மங்கலம்', type: 'Taluk', specialty: 'Paddy & Vegetables' },
      { en: 'K.Paramathi', ta: 'கே.பரமத்தி', type: 'Taluk', specialty: 'Millets, Cotton & Oilseeds' },
      { en: 'Kadavur', ta: 'கடவூர்', type: 'Taluk', specialty: 'Rainfed Pulses, Maize & Slender Loris sanctuary' },
    ],
    majorCrops: [
      { en: 'Drumstick (Moringa)', ta: 'முருங்கை' },
      { en: 'Banana (Poovan, Rasthali)', ta: 'வாழை' },
      { en: 'Paddy', ta: 'நெல்' },
      { en: 'Sugarcane', ta: 'கரும்பு' },
      { en: 'Cotton', ta: 'பருத்தி' },
      { en: 'Sesame', ta: 'எள்' },
    ],
    soilTypes: [
      { en: 'River Alluvium', ta: 'ஆற்று வண்டல் மண்' },
      { en: 'Red Sandy Loam', ta: 'செம்மண்' },
      { en: 'Black Cotton', ta: 'கரிசல் மண்' },
    ],
    annualRainfallMm: 652,
    waterBasinEn: 'Cauvery & Amaravathi Confluence',
    waterBasinTa: 'காவிரி & அமராவதி ஆற்றுப் படுகை',
    keyMandis: [
      { nameEn: 'Aravakurichi Moringa Mandi', nameTa: 'அரவக்குறிச்சி முருங்கை மொத்த சந்தை', type: 'Moringa Hub', speciality: 'Moringa & Drumstick Leaves' },
      { nameEn: 'Kulithalai Banana Regulated Market', nameTa: 'குளித்தலை வாழை ஒழுங்குமுறை விற்பனைக்கூடம்', type: 'Fruit Market', speciality: 'Banana bunches' },
    ],
    specialtyEn: 'Aravakurichi Moringa export hub feeding global markets and fertile Cauvery banana banks.',
    specialtyTa: 'உலகளவில் ஏற்றுமதியாகும் அரவக்குறிச்சி முருங்கை மற்றும் குளித்தலை வாழை சாகுபடி.',
    netCroppedAreaHa: 102000,
  },
  {
    id: 'krishnagiri',
    en: 'Krishnagiri',
    ta: 'கிருஷ்ணகிரி',
    capitalEn: 'Krishnagiri',
    capitalTa: 'கிருஷ்ணகிரி',
    zoneEn: 'North Western Agro Zone',
    zoneTa: 'வடமேற்கு வேளாண் மண்டலம்',
    coordinates: { lat: 12.5186, lng: 78.2137 },
    mainAreas: [
      { en: 'Hosur', ta: 'ஓசூர்', type: 'Taluk', specialty: 'Taj Mahal Roses & International Polyhouse Cut Flower Hub' },
      { en: 'Krishnagiri', ta: 'கிருஷ்ணகிரி', type: 'Taluk', specialty: 'Mango Pulp Capital of India (மாம்பழ கூழ்)' },
      { en: 'Rayakottai', ta: 'ராயக்கோட்டை', type: 'Agri Hub', specialty: 'Mega Tomato & Green Chilli Auction Market' },
      { en: 'Denkanikottai', ta: 'தேன்கனிக்கோட்டை', type: 'Taluk', specialty: 'Capsicum, Exotic Vegetables & Mulberry' },
      { en: 'Pochampalli', ta: 'போச்சம்பள்ளி', type: 'Taluk', specialty: 'Groundnut, Paddy & Weekly Agri Fair' },
      { en: 'Uthangarai', ta: 'ஊத்தங்கரை', type: 'Taluk', specialty: 'Millets, Samai & Sesame' },
      { en: 'Shoolagiri', ta: 'சூளகிரி', type: 'Taluk', specialty: 'Exotic Fruits, Melons & Dairy' },
      { en: 'Bargur', ta: 'பர்கூர்', type: 'Taluk', specialty: 'Bargur Cattle breed & Mango orchards' },
    ],
    majorCrops: [
      { en: 'Mango (Totapuri, Alphonso)', ta: 'மாம்பழம்' },
      { en: 'Cut Roses & Gerbera', ta: 'ரோஜா மலர்கள் & ஜெர்பரா' },
      { en: 'Tomato', ta: 'தக்காளி' },
      { en: 'Ragi & Millets', ta: 'கேழ்வரகு & சாமை' },
      { en: 'Capsicum & Broccoli', ta: 'குடைமிளகாய் & கோஸ்' },
      { en: 'Mulberry (Silk)', ta: 'பட்டுப்புழு மல்பெரி' },
    ],
    soilTypes: [
      { en: 'Red Sandy Loam', ta: 'செம்மண்' },
      { en: 'Lateritic Loam', ta: 'சரளை மண்' },
    ],
    annualRainfallMm: 842,
    waterBasinEn: 'Krishnagiri Reservoir Project (KRP Dam) & Thenpennai',
    waterBasinTa: 'கே.ஆர்.பி அணை & தென்பெண்ணை ஆறு',
    keyMandis: [
      { nameEn: 'Hosur International Flower Auction Center', nameTa: 'ஓசூர் சர்வதேச மலர் ஏல மையம்', type: 'Export Terminal', speciality: 'Cut Roses & Exotic Flowers' },
      { nameEn: 'Rayakottai Tomato Market', nameTa: 'ராயக்கோட்டை தக்காளி சந்தை', type: 'Agri Mandi', speciality: 'Tomato, Chilli & Capsicum' },
    ],
    specialtyEn: 'Global exporter of Hosur cut flowers, Valentine roses, and India’s premier mango processing hub.',
    specialtyTa: 'உலகத்தரம் வாய்ந்த ஓசூர் பசுமைக்குடில் ரோஜா மலர்கள் மற்றும் இந்தியாவின் முதன்மை மாம்பழக் கூழ் மையம்.',
    netCroppedAreaHa: 191000,
  },
  {
    id: 'madurai',
    en: 'Madurai',
    ta: 'மதுரை',
    capitalEn: 'Madurai',
    capitalTa: 'மதுரை',
    zoneEn: 'Southern Agro Zone / Vaigai Basin',
    zoneTa: 'தென் வேளாண் மண்டலம் / வைகை பாசனம்',
    coordinates: { lat: 9.9252, lng: 78.1198 },
    mainAreas: [
      { en: 'Vadipatti', ta: 'வாடிப்பட்டி', type: 'Taluk', specialty: 'Banana, Paddy & Vegetables' },
      { en: 'Melur', ta: 'மேலூர்', type: 'Taluk', specialty: 'Periyar main canal Paddy & Sugarcane' },
      { en: 'Thirumangalam', ta: 'திருமங்கலம்', type: 'Taluk', specialty: 'Cotton, Pulses & Groundnut' },
      { en: 'Usilampatti', ta: 'உசிலம்பட்டி', type: 'Taluk', specialty: 'Millets, Groundnut & Chilli' },
      { en: 'Peraiyur', ta: 'பேரையூர்', type: 'Taluk', specialty: 'Black cotton soil, Cotton & Pulses' },
      { en: 'Madurai East / Mattuthavani', ta: 'மாட்டுத்தாவணி', type: 'Agri Hub', specialty: 'Madurai Malli GI Flower Wholesale Market' },
      { en: 'Thiruparankundram', ta: 'திருப்பரங்குன்றம்', type: 'Taluk', specialty: 'Jasmine gardens & Betel vine' },
      { en: 'Kalligudi', ta: 'கள்ளிக்குடி', type: 'Taluk', specialty: 'Cotton & Dryland Agriculture' },
    ],
    majorCrops: [
      { en: 'Madurai Malli (GI Jasmine)', ta: 'மதுரை மல்லி (GI)' },
      { en: 'Paddy', ta: 'நெல்' },
      { en: 'Cotton', ta: 'பருத்தி' },
      { en: 'Pulses (Blackgram)', ta: 'உளுந்து' },
      { en: 'Banana', ta: 'வாழை' },
      { en: 'Guava (கொய்யா)', ta: 'கொய்யாப்பழம்' },
    ],
    soilTypes: [
      { en: 'Vaigai River Alluvium', ta: 'வைகை ஆற்று வண்டல்' },
      { en: 'Deep Black Cotton', ta: 'கரிசல் மண்' },
      { en: 'Red Sandy Loam', ta: 'செம்மண்' },
    ],
    annualRainfallMm: 840,
    waterBasinEn: 'Vaigai River Basin & Periyar Canal System',
    waterBasinTa: 'வைகை நதி & பெரியாறு பாசனக் கால்வாய்',
    keyMandis: [
      { nameEn: 'Mattuthavani Madurai Flower Market', nameTa: 'மாட்டுத்தாவணி மலர் அங்காடி', type: 'GI Flower Terminal', speciality: 'Madurai Malli (Jasmine)' },
      { nameEn: 'Vadipatti Banana Mandi', nameTa: 'வாடிப்பட்டி வாழை சந்தை', type: 'Fruit Market', speciality: 'Nendran & Poovan Banana' },
    ],
    specialtyEn: 'World-famous GI-tagged Madurai Malli (Jasmine perfume notes) and Vaigai river agricultural heritage.',
    specialtyTa: 'உலகப்புகழ் பெற்ற புவிசார் குறியீடு மதுரை மல்லி மற்றும் வரலாற்று சிறப்புமிக்க வைகை பாசனம்.',
    netCroppedAreaHa: 134000,
  },
  {
    id: 'mayiladuthurai',
    en: 'Mayiladuthurai',
    ta: 'மயிலாடுதுறை',
    capitalEn: 'Mayiladuthurai',
    capitalTa: 'மயிலாடுதுறை',
    zoneEn: 'Cauvery Delta Heartlands',
    zoneTa: 'காவிரி டெல்டா மையம்',
    coordinates: { lat: 11.1018, lng: 79.6522 },
    mainAreas: [
      { en: 'Mayiladuthurai', ta: 'மயிலாடுதுறை', type: 'Taluk', specialty: 'Kuruvai & Samba Paddy granary' },
      { en: 'Sirkazhi', ta: 'சீர்காழி', type: 'Taluk', specialty: 'Direct Paddy Procurement (DPC) & Pulses' },
      { en: 'Tharangambadi', ta: 'தரங்கம்பாடி', type: 'Taluk', specialty: 'Coastal Paddy, Groundnut & Coconut' },
      { en: 'Kuthalam', ta: 'குத்தாலம்', type: 'Taluk', specialty: 'Paddy, Sugarcane & Banana' },
      { en: 'Sembanarkoil', ta: 'செம்பனarkoil', type: 'Agri Hub', specialty: 'Rice seed farms & Blackgram' },
      { en: 'Poompuhar', ta: 'பூம்புகார்', type: 'Agri Hub', specialty: 'Coastal agriculture & Coconut' },
    ],
    majorCrops: [
      { en: 'Samba & Kuruvai Paddy', ta: 'சம்பா & குறுவை நெல்' },
      { en: 'Blackgram & Greengram', ta: 'உளுந்து & பாசிப்பயறு' },
      { en: 'Cotton (Rice Fallow)', ta: 'பருத்தி (நெல் தரிசு)' },
      { en: 'Sugarcane', ta: 'கரும்பு' },
      { en: 'Coconut', ta: 'தென்னை' },
    ],
    soilTypes: [
      { en: 'Deltaic Alluvial Clay', ta: 'டெல்டா வண்டல் களிமண்' },
      { en: 'Coastal Alluvium', ta: 'கடற்கரை வண்டல்' },
    ],
    annualRainfallMm: 1320,
    waterBasinEn: 'Cauvery Lower Reach & Coleroon River',
    waterBasinTa: 'காவிரி கடைமடை & கொள்ளிடம்',
    keyMandis: [
      { nameEn: 'Sirkazhi Regulated Market', nameTa: 'சீர்காழி ஒழுங்குமுறை விற்பனைக்கூடம்', type: 'Regulated Market', speciality: 'Paddy & Pulses' },
      { nameEn: 'Mayiladuthurai Grain Mandi', nameTa: 'மயிலாடுதுறை தானிய மண்டி', type: 'Grain Terminal', speciality: 'Kuruvai Paddy & Blackgram' },
    ],
    specialtyEn: 'Epicenter of Cauvery delta double-cropping system, famous for Samba rice and rice-fallow blackgram.',
    specialtyTa: 'காவிரி டெல்டா இருபோக நெல் சாகுபடி மையம், சம்பா நெல் மற்றும் நெல் தரிசு உளுந்து விளைச்சல்.',
    netCroppedAreaHa: 108000,
  },
  {
    id: 'nagapattinam',
    en: 'Nagapattinam',
    ta: 'நாகப்பட்டினம்',
    capitalEn: 'Nagapattinam',
    capitalTa: 'நாகப்பட்டினம்',
    zoneEn: 'Cauvery Delta Coastal Zone',
    zoneTa: 'காவிரி டெல்டா கடலோர மண்டலம்',
    coordinates: { lat: 10.7670, lng: 79.8420 },
    mainAreas: [
      { en: 'Nagapattinam', ta: 'நாகப்பட்டினம்', type: 'Taluk', specialty: 'Coastal paddy & fisheries interface' },
      { en: 'Kilvelur', ta: 'கீழ்வேளூர்', type: 'Taluk', specialty: 'Prime Paddy cultivation & DPC centers' },
      { en: 'Vedaranyam', ta: 'வேதாரண்யம்', type: 'Taluk', specialty: 'Salt pan agriculture, Coconut & Mango' },
      { en: 'Thirukkuvalai', ta: 'திருக்குவளை', type: 'Taluk', specialty: 'Paddy, Blackgram & Cotton' },
      { en: 'Thalainayar', ta: 'தலைஞாயிறு', type: 'Agri Hub', specialty: 'Organic saline-resistant Paddy varieties' },
    ],
    majorCrops: [
      { en: 'Paddy (CR 1009, White Ponni)', ta: 'நெல் (CR 1009, பொன்னி)' },
      { en: 'Pulses (Blackgram, Moong)', ta: 'பயறு வகைகள்' },
      { en: 'Cotton', ta: 'பருத்தி' },
      { en: 'Coconut', ta: 'தென்னை' },
    ],
    soilTypes: [
      { en: 'Coastal Alluvium', ta: 'கடற்கரை வண்டல் மண்' },
      { en: 'Saline Alkaline Loam', ta: 'உவர் கலந்த வண்டல்' },
      { en: 'Heavy Clay', ta: 'கனத்த களிமண்' },
    ],
    annualRainfallMm: 1340,
    waterBasinEn: 'Cauvery Tail-end Riverlets & Vedaranyam Canal',
    waterBasinTa: 'காவிரி கடைமடை ஆறுகள் & வேதாரண்யம் கால்வாய்',
    keyMandis: [
      { nameEn: 'Nagapattinam Regulated Market', nameTa: 'நாகப்பட்டினம் ஒழுங்குமுறை விற்பனைக்கூடம்', type: 'Regulated Market', speciality: 'Paddy & Pulses' },
      { nameEn: 'Vedaranyam Coastal Produce Mandi', nameTa: 'வேதாரண்யம் விளைபொருள் அங்காடி', type: 'Coastal Market', speciality: 'Coconut & Mango' },
    ],
    specialtyEn: 'Tail-end Cauvery irrigation, pioneer in saline-tolerant CR-1009 Sub-1 flood-resilient paddy.',
    specialtyTa: 'காவிரி கடைமடை பாசனம் மற்றும் வெள்ளத்தை தாங்கி வளரும் பாரம்பரிய நெல் ரகங்கள்.',
    netCroppedAreaHa: 96000,
  },
  {
    id: 'namakkal',
    en: 'Namakkal',
    ta: 'நாமக்கல்',
    capitalEn: 'Namakkal',
    capitalTa: 'நாமக்கல்',
    zoneEn: 'North Western Agro Zone',
    zoneTa: 'வடமேற்கு வேளாண் மண்டலம்',
    coordinates: { lat: 11.2189, lng: 78.1674 },
    mainAreas: [
      { en: 'Paramathi Velur', ta: 'பரமத்தி வேலூர்', type: 'Taluk', specialty: 'Betel Vine (வெற்றிலை) & Banana along Cauvery' },
      { en: 'Rasipuram', ta: 'ராசிபுரம்', type: 'Taluk', specialty: 'Sago (ஜவ்வரிசி), Tapioca & Ghee' },
      { en: 'Tiruchengode', ta: 'திருச்செங்கோடு', type: 'Taluk', specialty: 'Borewell equipment, Groundnut & Millets' },
      { en: 'Kolli Hills (Kolli Malai)', ta: 'கொல்லிமலை', type: 'Taluk', specialty: 'Organic Pepper, Pineapple, Coffee & Medicinal Herbs' },
      { en: 'Namakkal', ta: 'நாமக்கல்', type: 'Taluk', specialty: 'Poultry Capital of India, Maize & Feed crops' },
      { en: 'Mohanur', ta: 'மோகனூர்', type: 'Taluk', specialty: 'Cooperative Sugar Mills & Sugarcane' },
      { en: 'Sendamangalam', ta: 'சேந்தமங்கலம்', type: 'Taluk', specialty: 'Tapioca & Red Onion' },
    ],
    majorCrops: [
      { en: 'Poultry Feed & Maize', ta: 'மக்காச்சோளம் & கோழித்தீவனம்' },
      { en: 'Tapioca / Sago', ta: 'மரவள்ளிக்கிழங்கு / ஜவ்வரிசி' },
      { en: 'Betel Vine (வெற்றிலை)', ta: 'வெற்றிலை' },
      { en: 'Kolli Hills Pepper & Pineapple', ta: 'கொல்லிமலை மிளகு & அன்னாசி' },
      { en: 'Sugarcane', ta: 'கரும்பு' },
      { en: 'Banana', ta: 'வாழை' },
    ],
    soilTypes: [
      { en: 'Red Sandy Loam', ta: 'செம்மண்' },
      { en: 'Hill Forest Loam', ta: 'மலைக் காடு மண்' },
      { en: 'Gravelly Clay', ta: 'சரளை மண்' },
    ],
    annualRainfallMm: 780,
    waterBasinEn: 'Cauvery River & Thirumanimutharu Basin',
    waterBasinTa: 'காவிரி நதி & திருமணிமுத்தாறு',
    keyMandis: [
      { nameEn: 'Paramathi Velur Betel Vine Market', nameTa: 'பரமத்தி வேலூர் வெற்றிலை சந்தை', type: 'National Mandi', speciality: 'Vellai & Karuppu Vettilai' },
      { nameEn: 'Rasipuram Sago & Tapioca Market', nameTa: 'ராசிபுரம் ஜவ்வரிசி & மரவள்ளி சந்தை', type: 'Agro Industrial', speciality: 'Tapioca starch & Sago' },
    ],
    specialtyEn: 'Egg & Poultry capital of Asia, Paramathi Velur GI betel vine, and Kolli Hills organic spice paradise.',
    specialtyTa: 'ஆசியாவின் முட்டை தலைநகரம், பரமத்தி வேலூர் வெற்றிலை மற்றும் கொல்லிமலை மிளகு, அன்னாசி.',
    netCroppedAreaHa: 154000,
  },
  {
    id: 'nilgiris',
    en: 'Nilgiris',
    ta: 'நீலகிரி',
    capitalEn: 'Udhagamandalam (Ooty)',
    capitalTa: 'உதகமண்டலம் (ஊட்டி)',
    zoneEn: 'High Altitude Hill Zone',
    zoneTa: 'உயர்மலை வேளாண் மண்டலம்',
    coordinates: { lat: 11.4102, lng: 76.6950 },
    mainAreas: [
      { en: 'Ooty (Udhagamandalam)', ta: 'ஊட்டி', type: 'Taluk', specialty: 'Carrot, Potato, Cabbage & Exotic Veggies' },
      { en: 'Coonoor', ta: 'குன்னூர்', type: 'Taluk', specialty: 'Nilgiri Orthodox Tea (GI) & Fruit orchards' },
      { en: 'Kotagiri', ta: 'கோத்தகிரி', type: 'Taluk', specialty: 'Organic Tea estates, Garlic & Cabbage' },
      { en: 'Gudalur', ta: 'கூடலூர்', type: 'Taluk', specialty: 'Coffee, Pepper, Cardamom, Ginger & Tea' },
      { en: 'Kundah', ta: 'குந்தா', type: 'Taluk', specialty: 'Hydro reservoirs & Mountain farming' },
      { en: 'Pandalur', ta: 'பந்தலூர்', type: 'Taluk', specialty: 'Spices & Small Tea Growers' },
    ],
    majorCrops: [
      { en: 'Nilgiri Orthodox Tea (GI)', ta: 'நீலகிரி தேயிலை (GI)' },
      { en: 'Hill Carrot & Potato', ta: 'கேரட் & உருளைக்கிழங்கு' },
      { en: 'Coffee (Arabica / Robusta)', ta: 'காபி' },
      { en: 'Eucalyptus & Essential Oils', ta: 'யூகலிப்டஸ் தைலம்' },
      { en: 'Spices (Pepper, Cardamom)', ta: 'மிளகு & ஏலக்காய்' },
    ],
    soilTypes: [
      { en: 'Mountain Peaty Soil', ta: 'மலைக் கரிசல் / அங்கக மண்' },
      { en: 'Laterite Soil', ta: 'சரளை மண்' },
      { en: 'Acidic Loam', ta: 'அமிலத் தன்மை கொண்ட மண்' },
    ],
    annualRainfallMm: 1780,
    waterBasinEn: 'Bhavani, Moyar, Pykara & Kabini River Basins',
    waterBasinTa: 'பவானி, மாயாறு, பைகாரா & கபினி படுகை',
    keyMandis: [
      { nameEn: 'Coonoor Tea Trade Auction Center', nameTa: 'குன்னூர் தேயிலை வர்த்தக ஏல மையம்', type: 'International Auction', speciality: 'Nilgiri Orthodox & CTC Tea' },
      { nameEn: 'Mettupalayam Nilgiri Veg Mandi', nameTa: 'மேட்டுப்பாளையம் நீலகிரி காய்கறி மண்டி', type: 'Wholesale Mandi', speciality: 'Ooty Carrot, Potato, Beetroot' },
    ],
    specialtyEn: 'GI-certified Nilgiri Orthodox Tea, washed sweet Ooty carrots, and temperate hill horticulture.',
    specialtyTa: 'GI அங்கீகாரம் பெற்ற நீலகிரி தேயிலை, ஊட்டி கழுவிய காரட் மற்றும் மிதமான குளிர்கால காய்கறி சாகுபடி.',
    netCroppedAreaHa: 79000,
  },
  {
    id: 'perambalur',
    en: 'Perambalur',
    ta: 'பெரம்பலூர்',
    capitalEn: 'Perambalur',
    capitalTa: 'பெரம்பலூர்',
    zoneEn: 'Cauvery Marginal / North Eastern Zone',
    zoneTa: 'வடகிழக்கு / மத்திய மண்டலம்',
    coordinates: { lat: 11.2340, lng: 78.8820 },
    mainAreas: [
      { en: 'Veppanthattai', ta: 'வேப்பந்தட்டை', type: 'Taluk', specialty: 'Cotton, Maize & TNAU Research Station' },
      { en: 'Chettikulam', ta: 'செட்டிக்குளம்', type: 'Agri Hub', specialty: 'Shallots / Small Onion (சின்ன வெங்காயம்) Hub' },
      { en: 'Kunnam', ta: 'குன்னம்', type: 'Taluk', specialty: 'Black soil Cotton, Maize & Millets' },
      { en: 'Alathur', ta: 'ஆலத்தூர்', type: 'Taluk', specialty: 'Sugarcane, Groundnut & Dairy' },
      { en: 'Perambalur', ta: 'பெரம்பலூர்', type: 'Taluk', specialty: 'Maize Processing & Cotton ginning' },
    ],
    majorCrops: [
      { en: 'Small Onion / Shallots', ta: 'சின்ன வெங்காயம் (தமிழக தலைநகரம்)' },
      { en: 'Maize (Corn)', ta: 'மக்காச்சோளம்' },
      { en: 'Cotton', ta: 'பருத்தி' },
      { en: 'Sugarcane', ta: 'கரும்பு' },
      { en: 'Groundnut', ta: 'நிலக்கடலை' },
    ],
    soilTypes: [
      { en: 'Deep Black Cotton', ta: 'கரிசல் மண்' },
      { en: 'Red Sandy Loam', ta: 'செம்மண்' },
    ],
    annualRainfallMm: 865,
    waterBasinEn: 'Vellar River & Marudhaiyar Sub-basin',
    waterBasinTa: 'வெள்ளாறு & மருதையாறு பாசனம்',
    keyMandis: [
      { nameEn: 'Chettikulam Small Onion Market', nameTa: 'செட்டிக்குளம் சின்ன வெங்காய சந்தை', type: 'Specialized Mandi', speciality: 'Shallots / Small Onion' },
      { nameEn: 'Perambalur Maize Regulated Market', nameTa: 'பெரம்பலூர் மக்காச்சோள ஒழுங்குமுறை கூடம்', type: 'Regulated Market', speciality: 'Maize & Cotton' },
    ],
    specialtyEn: 'Small Onion (Shallots) Capital of Tamil Nadu, producing 25% of the state’s shallots.',
    specialtyTa: 'தமிழகத்தின் சின்ன வெங்காய தலைநகரம்; மாநில உற்பத்தியில் 25% சின்ன வெங்காயம் இங்கு விளைகிறது.',
    netCroppedAreaHa: 98000,
  },
  {
    id: 'pudukkottai',
    en: 'Pudukkottai',
    ta: 'புதுக்கோட்டை',
    capitalEn: 'Pudukkottai',
    capitalTa: 'புதுக்கோட்டை',
    zoneEn: 'Southern Agro Zone & Coastal Belt',
    zoneTa: 'தென் வேளாண் மண்டலம் & கடற்கரை',
    coordinates: { lat: 10.3833, lng: 78.8001 },
    mainAreas: [
      { en: 'Alangudi', ta: 'ஆலங்குடி', type: 'Taluk', specialty: 'Groundnut & Cashew Capital' },
      { en: 'Aranthangi', ta: 'அறந்தாங்கி', type: 'Taluk', specialty: 'Delta tail-end Paddy & Aqua farming' },
      { en: 'Gandarvakottai', ta: 'கந்தர்வக்கோட்டை', type: 'Taluk', specialty: 'Cashew plantations & Groundnut' },
      { en: 'Thirumayam', ta: 'திருமயம்', type: 'Taluk', specialty: 'Millets, Pulses & Red soil dryland' },
      { en: 'Viralimalai', ta: 'விராலிமலை', type: 'Taluk', specialty: 'Vegetables & Floriculture' },
      { en: 'Illuppur', ta: 'இல்லுப்பூர்', type: 'Taluk', specialty: 'Dairy farming & Groundnut' },
      { en: 'Ponnamaravathi', ta: 'பொன்னமராவதி', type: 'Taluk', specialty: 'Paddy & Coconut groves' },
      { en: 'Karambakkudi', ta: 'கறம்பக்குடி', type: 'Taluk', specialty: 'Paddy, Groundnut & Tapioca' },
    ],
    majorCrops: [
      { en: 'Groundnut', ta: 'நிலக்கடலை' },
      { en: 'Paddy', ta: 'நெல்' },
      { en: 'Cashew', ta: 'முந்திரி' },
      { en: 'Coconut', ta: 'தென்னை' },
      { en: 'Blackgram', ta: 'உளுந்து' },
      { en: 'Small Millets', ta: 'சிறு தானியங்கள்' },
    ],
    soilTypes: [
      { en: 'Red Lateritic Loam', ta: 'செம்மண் சரளை' },
      { en: 'Sandy Loam', ta: 'மணல் கலந்த வண்டல்' },
      { en: 'Coastal Alluvium', ta: 'கடற்கரை வண்டல்' },
    ],
    annualRainfallMm: 921,
    waterBasinEn: 'Agniyar, Ambuliyar & Vellar Basins',
    waterBasinTa: 'அக்னியாறு, அம்புலியாறு & வெள்ளாறு',
    keyMandis: [
      { nameEn: 'Alangudi Groundnut Market', nameTa: 'ஆலங்குடி கடலை சந்தை', type: 'Regulated Market', speciality: 'Groundnut & Cashew' },
      { nameEn: 'Aranthangi Paddy Market', nameTa: 'அறந்தாங்கி நெல் கொள்முதல் மண்டி', type: 'Regulated Market', speciality: 'Samba Paddy' },
    ],
    specialtyEn: 'Prime groundnut and cashew processing belt with unique red laterite soil agriculture.',
    specialtyTa: 'முதன்மையான நிலக்கடலை மற்றும் முந்திரி சாகுபடி மையம், செம்மண் சரளை நில வளம்.',
    netCroppedAreaHa: 162000,
  },
  {
    id: 'ramanathapuram',
    en: 'Ramanathapuram',
    ta: 'ராமநாதபுரம்',
    capitalEn: 'Ramanathapuram',
    capitalTa: 'ராமநாதபுரம்',
    zoneEn: 'Coastal Saline Dry Zone',
    zoneTa: 'கடலோர உவர் வறண்ட மண்டலம்',
    coordinates: { lat: 9.3639, lng: 78.8395 },
    mainAreas: [
      { en: 'Paramakudi', ta: 'பரமக்குடி', type: 'Taluk', specialty: 'Ramnad Mundu Chilli (குண்டு மிளகாய் GI) Hub' },
      { en: 'Kamuthi', ta: 'கமுதி', type: 'Taluk', specialty: 'Rainfed Cotton, Blackgram & Solar agrivoltaics' },
      { en: 'Mudukulathur', ta: 'முதுகுளத்தூர்', type: 'Taluk', specialty: 'Dryland Paddy & Millets' },
      { en: 'RS Mangalam (Rajasingamangalam)', ta: 'ஆர்.எஸ்.மங்கலம்', type: 'Taluk', specialty: 'Second largest irrigation tank in TN & Paddy' },
      { en: 'Thiruvadanai', ta: 'திருவாடனை', type: 'Taluk', specialty: 'Rainfed Paddy & Cotton' },
      { en: 'Rameswaram', ta: 'ராமேஸ்வரம்', type: 'Taluk', specialty: 'Island Coconut & Palmyra' },
      { en: 'Kadaladi', ta: 'கடலாடி', type: 'Taluk', specialty: 'Palmyra jaggery & Sesame' },
    ],
    majorCrops: [
      { en: 'Ramnad Mundu Chilli (GI)', ta: 'ராமநாதபுரம் குண்டு மிளகாய் (GI)' },
      { en: 'Rainfed Paddy', ta: 'மானாவாரி நெல்' },
      { en: 'Cotton', ta: 'பருத்தி' },
      { en: 'Palmyra Products', ta: 'பனை பொருட்கள் & கருப்பட்டி' },
      { en: 'Blackgram', ta: 'உளுந்து' },
    ],
    soilTypes: [
      { en: 'Coastal Alluvium', ta: 'கடற்கரை வண்டல்' },
      { en: 'Saline Clay', ta: 'உவர் களிமண்' },
      { en: 'Red Sandy Soil', ta: 'செம்மண்' },
    ],
    annualRainfallMm: 825,
    waterBasinEn: 'Vaigai Tail-end & RS Mangalam Big Tank',
    waterBasinTa: 'வைகை கடைமடை & ஆர்.எஸ்.மங்கலம் பெரிய கண்மாய்',
    keyMandis: [
      { nameEn: 'Paramakudi Chilli Regulated Market', nameTa: 'பரமக்குடி மிளகாய் ஒழுங்குமுறை விற்பனைக்கூடம்', type: 'GI Commodity Mandi', speciality: 'Ramnad Mundu Chilli' },
      { nameEn: 'Kamuthi Cotton Mandi', nameTa: 'கமுதி பருத்தி சந்தை', type: 'Regulated Market', speciality: 'Cotton & Pulses' },
    ],
    specialtyEn: 'GI Tag Ramnad Mundu Chilli (round pungent pepper) and ancient giant irrigation kanmois.',
    specialtyTa: 'புவிசார் குறியீடு பெற்ற காரசார ராமநாதபுரம் குண்டு மிளகாய் மற்றும் வரலாற்று கண்மாய்கள்.',
    netCroppedAreaHa: 178000,
  },
  {
    id: 'ranipet',
    en: 'Ranipet',
    ta: 'ராணிப்பேட்டை',
    capitalEn: 'Ranipet',
    capitalTa: 'ராணிப்பேட்டை',
    zoneEn: 'North Eastern Zone',
    zoneTa: 'வடகிழக்கு வேளாண் மண்டலம்',
    coordinates: { lat: 12.9298, lng: 79.3332 },
    mainAreas: [
      { en: 'Walajah', ta: 'வாலாஜா', type: 'Taluk', specialty: 'Paddy, Groundnut & Vegetables' },
      { en: 'Arcot', ta: 'ஆற்காடு', type: 'Taluk', specialty: 'Palar riverbed Paddy, Banana & Sugarcane' },
      { en: 'Sholinghur', ta: 'சோளிங்கர்', type: 'Taluk', specialty: 'Groundnut, Mango & Hill Vegetables' },
      { en: 'Arakkonam', ta: 'அரக்கோணம்', type: 'Taluk', specialty: 'Paddy & Watermelon' },
      { en: 'Nemili', ta: 'நெமிலி', type: 'Taluk', specialty: 'Kaveripakkam tank ayacut Paddy' },
      { en: 'Kaveripakkam', ta: 'காவேரிப்பாக்கம்', type: 'Agri Hub', specialty: 'Historic Kaveripakkam Lake, Paddy & Fish' },
    ],
    majorCrops: [
      { en: 'Paddy', ta: 'நெல்' },
      { en: 'Groundnut', ta: 'நிலக்கடலை' },
      { en: 'Sugarcane', ta: 'கரும்பு' },
      { en: 'Watermelon', ta: 'தர்பூசணி' },
      { en: 'Banana', ta: 'வாழை' },
    ],
    soilTypes: [
      { en: 'Red Sandy Loam', ta: 'செம்மண்' },
      { en: 'Palar River Alluvium', ta: 'பாலாற்று வண்டல்' },
    ],
    annualRainfallMm: 1040,
    waterBasinEn: 'Palar River & Kaveripakkam Big Lake',
    waterBasinTa: 'பாலாறு & காவேரிப்பாக்கம் பெரிய ஏரி',
    keyMandis: [
      { nameEn: 'Arcot Regulated Market', nameTa: 'ஆற்காடு ஒழுங்குமுறை விற்பனைக்கூடம்', type: 'Regulated Market', speciality: 'Paddy & Groundnut' },
      { nameEn: 'Sholinghur Agri Market', nameTa: 'சோளிங்கர் வேளாண் சந்தை', type: 'Agri Market', speciality: 'Mango & Banana' },
    ],
    specialtyEn: 'Historic Kaveripakkam Lake irrigation feeding tens of thousands of paddy acres.',
    specialtyTa: 'காவேரிப்பாக்கம் வரலாற்று சிறப்புமிக்க பெரிய ஏரி பாசனம் மற்றும் செழுமையான நெல் சாகுபடி.',
    netCroppedAreaHa: 94000,
  },
  {
    id: 'salem',
    en: 'Salem',
    ta: 'சேலம்',
    capitalEn: 'Salem',
    capitalTa: 'சேலம்',
    zoneEn: 'North Western Zone & Shevaroy Foothills',
    zoneTa: 'வடமேற்கு வேளாண் மண்டலம் & சேர்வராயன் மலை',
    coordinates: { lat: 11.6643, lng: 78.1460 },
    mainAreas: [
      { en: 'Attur', ta: 'ஆத்தூர்', type: 'Taluk', specialty: 'Sago / Tapioca (ஜவ்வரிசி) Capital of India' },
      { en: 'Yercaud', ta: 'ஏற்காடு', type: 'Taluk', specialty: 'Shevaroy Coffee, Black Pepper, Orange & Spices' },
      { en: 'Mettur', ta: 'மேட்டூர்', type: 'Taluk', specialty: 'Stanley Reservoir (Mettur Dam), Fisheries & Banana' },
      { en: 'Omalur', ta: 'ஓமலூர்', type: 'Taluk', specialty: 'Salem Malgova Mango orchards & Silk' },
      { en: 'Edappadi', ta: 'எடப்பாடி', type: 'Taluk', specialty: 'Sugarcane, Groundnut & Drip Banana' },
      { en: 'Sankari', ta: 'சங்ககிரி', type: 'Taluk', specialty: 'Millets, Maize & Poultry' },
      { en: 'Vazhapadi', ta: 'வாழப்பாடி', type: 'Taluk', specialty: 'Tapioca & Arecanut' },
      { en: 'Gangavalli', ta: 'கங்கவல்லி', type: 'Taluk', specialty: 'Maize & Cotton' },
    ],
    majorCrops: [
      { en: 'Salem Mango (Malgova GI)', ta: 'சேலம் மாம்பழம் (மல்கோவா GI)' },
      { en: 'Tapioca & Sago', ta: 'மரவள்ளிக்கிழங்கு & ஜவ்வரிசி' },
      { en: 'Shevaroy Coffee & Pepper', ta: 'ஏற்காடு காபி & மிளகு' },
      { en: 'Sugarcane', ta: 'கரும்பு' },
      { en: 'Turmeric', ta: 'மஞ்சள்' },
    ],
    soilTypes: [
      { en: 'Red Gravelly Loam', ta: 'செம்மண் சரளை' },
      { en: 'Black Loam', ta: 'கரிசல் மண்' },
      { en: 'Mountain Forest Soil', ta: 'மலைக் காடு மண்' },
    ],
    annualRainfallMm: 980,
    waterBasinEn: 'Cauvery River (Mettur Stanley Dam) & Vashista River',
    waterBasinTa: 'காவிரி (மேட்டூர் அணை) & வசிஷ்ட நதி',
    keyMandis: [
      { nameEn: 'Attur Sago & Starch Market (SAGOSERVE)', nameTa: 'ஆத்தூர் சாகோசர்வ் ஜவ்வரிசி அங்காடி', type: 'Apex Commodity Board', speciality: 'Sago & Starch' },
      { nameEn: 'Salem Shevapet Mango Wholesale Market', nameTa: 'சேலம் செவ்வாய்பேட்டை மாம்பழ சந்தை', type: 'Fruit Terminal', speciality: 'Salem Mangoes' },
    ],
    specialtyEn: 'Famous for GI Salem Malgova Mango, SAGOSERVE Tapioca monopoly, and Stanley Dam irrigation anchor.',
    specialtyTa: 'சுவைமிகு சேலம் மாம்பழம், இந்தியாவின் 80% ஜவ்வரிசி தயாரிக்கும் சாகோசர்வ் மற்றும் மேட்டூர் அணை.',
    netCroppedAreaHa: 220000,
  },
  {
    id: 'sivaganga',
    en: 'Sivaganga',
    ta: 'சிவகங்கை',
    capitalEn: 'Sivaganga',
    capitalTa: 'சிவகங்கை',
    zoneEn: 'Southern Dry Zone',
    zoneTa: 'தென் வறண்ட மண்டலம்',
    coordinates: { lat: 9.8433, lng: 78.4809 },
    mainAreas: [
      { en: 'Karaikudi', ta: 'காரைக்குடி', type: 'Taluk', specialty: 'Chettinad heritage, Millets & Paddy' },
      { en: 'Singampunari', ta: 'சிங்கம்புணரி', type: 'Taluk', specialty: 'Groundnut, Coconut & Palmyrah hub' },
      { en: 'Manamadurai', ta: 'மானாமதுரை', type: 'Taluk', specialty: 'Vaigai river clay, Pottery & Chilli' },
      { en: 'Devakottai', ta: 'தேவகோட்டை', type: 'Taluk', specialty: 'Rainfed Paddy & Pulses' },
      { en: 'Tiruppuvanam', ta: 'திருப்புவனம்', type: 'Taluk', specialty: 'Vaigai Basin Sugarcane & Paddy' },
      { en: 'Ilayangudi', ta: 'இளையான்குடி', type: 'Taluk', specialty: 'Chilli, Groundnut & Sesame' },
      { en: 'Kalaiyarkoil', ta: 'காளையார்கோவில்', type: 'Taluk', specialty: 'Dryland Paddy & Small millets' },
    ],
    majorCrops: [
      { en: 'Paddy', ta: 'நெல்' },
      { en: 'Groundnut', ta: 'நிலக்கடலை' },
      { en: 'Chilli', ta: 'மிளகாய்' },
      { en: 'Coconut', ta: 'தென்னை' },
      { en: 'Sugarcane', ta: 'கரும்பு' },
      { en: 'Pulses', ta: 'பயறு வகைகள்' },
    ],
    soilTypes: [
      { en: 'Red Sandy Loam', ta: 'செம்மண்' },
      { en: 'Laterite Soil', ta: 'சரளை மண்' },
      { en: 'River Alluvium', ta: 'ஆற்று வண்டல்' },
    ],
    annualRainfallMm: 904,
    waterBasinEn: 'Vaigai, Sarugani & Manimuthar River Basins',
    waterBasinTa: 'வைகை, சருகணியாறு & மணிமுத்தாறு',
    keyMandis: [
      { nameEn: 'Singampunari Groundnut & Coconut Market', nameTa: 'சிங்கம்புணரி கடலை & தேங்காய் சந்தை', type: 'Regulated Market', speciality: 'Groundnut & Copra' },
      { nameEn: 'Manamadurai Agro Produce Mandi', nameTa: 'மானாமதுரை விளைபொருள் அங்காடி', type: 'Regulated Market', speciality: 'Chilli & Grain' },
    ],
    specialtyEn: 'Rich Chettinad tank-based agriculture, Singampunari groundnut center and Vaigai fertile reaches.',
    specialtyTa: 'செட்டிநாட்டு பாரம்பரிய கண்மாய் பாசனம், சிங்கம்புணரி நிலக்கடலை மற்றும் வைகை பாசனம்.',
    netCroppedAreaHa: 135000,
  },
  {
    id: 'tenkasi',
    en: 'Tenkasi',
    ta: 'தென்காசி',
    capitalEn: 'Tenkasi',
    capitalTa: 'தென்காசி',
    zoneEn: 'Western Ghats Transition Zone',
    zoneTa: 'மேற்கு தொடர்ச்சி மலை அடிவார மண்டலம்',
    coordinates: { lat: 8.9594, lng: 77.3150 },
    mainAreas: [
      { en: 'Sankarankovil', ta: 'சங்கரன்கோவில்', type: 'Taluk', specialty: 'Gomathi Amman Flower Market & Cotton' },
      { en: 'Kadayanallur / Puliangudi', ta: 'புளியங்குடி', type: 'Taluk', specialty: 'Lemon Capital of Tamil Nadu (எலுமிச்சை நகரம்)' },
      { en: 'Sengottai', ta: 'செங்கோட்டை', type: 'Taluk', specialty: 'Western Ghats Spices, Mango & Banana' },
      { en: 'Tenkasi', ta: 'தென்காசி', type: 'Taluk', specialty: 'Chittar River Paddy, Sugarcane & Guava' },
      { en: 'Alangulam', ta: 'ஆலங்குளம்', type: 'Taluk', specialty: 'Vegetables & Onion cultivation' },
      { en: 'Sivagiri', ta: 'சிவகிரி', type: 'Taluk', specialty: 'Sugarcane & Paddy' },
      { en: 'Shenkottai Gap', ta: 'ஆரியங்காவு கணவாய்', type: 'Agri Hub', specialty: 'Cardamom & Pepper trade' },
    ],
    majorCrops: [
      { en: 'Lemon (Puliangudi Lime)', ta: 'எலுமிச்சை (புளியங்குடி)' },
      { en: 'Samba & Kar Paddy', ta: 'கார் & சம்பா நெல்' },
      { en: 'Mango (Alphonso, Banganapalli)', ta: 'மாம்பழம்' },
      { en: 'Sugarcane', ta: 'கரும்பு' },
      { en: 'Spices & Pepper', ta: 'மிளகு & நறுமணப் பயிர்கள்' },
      { en: 'Flowers (Crossandra / Jasmine)', ta: 'பூக்கள்' },
    ],
    soilTypes: [
      { en: 'Red Sandy Loam', ta: 'செம்மண்' },
      { en: 'Deep Black Cotton', ta: 'கரிசல் மண்' },
      { en: 'Ghat Foothill Alluvium', ta: 'மலை அடிவார வண்டல்' },
    ],
    annualRainfallMm: 1120,
    waterBasinEn: 'Chittar, Hariharanadhi & Gundar Dams',
    waterBasinTa: 'சிற்றாறு, அரிகரநதி & குண்டாறு அணை',
    keyMandis: [
      { nameEn: 'Puliangudi Lemon Wholesale Market', nameTa: 'புளியங்குடி எலுமிச்சை மொத்த சந்தை', type: 'National Mandi', speciality: 'Juicy Acid Lime (daily 100+ tons)' },
      { nameEn: 'Sankarankovil Flower Market', nameTa: 'சங்கரன்கோவில் பூக்கள் சந்தை', type: 'Flower Mandi', speciality: 'Kanakambaram & Jasmine' },
    ],
    specialtyEn: 'Puliangudi Lemon Capital, Courtallam microclimate, and perennial Chittar river basin farming.',
    specialtyTa: 'தமிழகத்தின் எலுமிச்சை தலைநகரம் புளியங்குடி மற்றும் குற்றால சாரல் வளர்க்கும் வேளாண்மை.',
    netCroppedAreaHa: 122000,
  },
  {
    id: 'thanjavur',
    en: 'Thanjavur',
    ta: 'தஞ்சாவூர்',
    capitalEn: 'Thanjavur',
    capitalTa: 'தஞ்சாவூர்',
    zoneEn: 'Cauvery Delta Heartland',
    zoneTa: 'காவிரி டெல்டா நெற்களஞ்சியம்',
    coordinates: { lat: 10.7870, lng: 79.1378 },
    mainAreas: [
      { en: 'Thiruvaiyaru', ta: 'திருவையாறு', type: 'Taluk', specialty: 'Panchanadeeswarar Cauvery belt, Samba Paddy & Bananas' },
      { en: 'Kumbakonam', ta: 'கும்பகோணம்', type: 'Taluk', specialty: 'Betel Vine (கும்பகோணம் வெற்றிலை), Paddy & Rice mills' },
      { en: 'Orathanadu', ta: 'ஒரத்தநாடு', type: 'Taluk', specialty: 'Grand Anicut Canal ayacut, Dairy & Paddy' },
      { en: 'Pattukkottai', ta: 'பட்டுக்கோட்டை', type: 'Taluk', specialty: 'Coastal Coconut Capital, Copra & Groundnut' },
      { en: 'Papanasam', ta: 'பாபநாசம்', type: 'Taluk', specialty: 'Kuruvai Paddy & Banana groves' },
      { en: 'Budalur', ta: 'பூதலூர்', type: 'Taluk', specialty: 'Grand Anicut (கல்லணை) headworks & Paddy' },
      { en: 'Peravurani', ta: 'பேராவூரணி', type: 'Taluk', specialty: 'Coconut plantations & Coir industry' },
      { en: 'Thiruvidaimarudur', ta: 'திருவிடைமருதூர்', type: 'Taluk', specialty: 'Organic heirloom rice & Sugarcane' },
    ],
    majorCrops: [
      { en: 'Kuruvai & Samba Paddy (Ponni, CR 1009)', ta: 'குறுவை & சம்பா நெல் (பொன்னி, CR 1009)' },
      { en: 'Coconut (Pattukkottai)', ta: 'தென்னை' },
      { en: 'Blackgram & Greengram', ta: 'உளுந்து & பாசிப்பயறு' },
      { en: 'Sugarcane', ta: 'கரும்பு' },
      { en: 'Banana (Poovan, Rasthali)', ta: 'வாழை' },
      { en: 'Betel Vine', ta: 'வெற்றிலை' },
    ],
    soilTypes: [
      { en: 'Deep Cauvery Alluvial Loam', ta: 'காவிரி வண்டல் மண்' },
      { en: 'Clay Loam', ta: 'களிமண் வண்டல்' },
      { en: 'Coastal Sand (Pattukkottai)', ta: 'கடற்கரை மணல்' },
    ],
    annualRainfallMm: 1045,
    waterBasinEn: 'Cauvery River, Vennar, Grand Anicut Canal & Coleroon',
    waterBasinTa: 'காவிரி, வெண்ணாறு, கல்லணைக் கால்வாய் & கொள்ளிடம்',
    keyMandis: [
      { nameEn: 'Thiruvaiyaru DPC Paddy Center', nameTa: 'திருவையாறு நேரடி நெல் கொள்முதல் நிலையம்', type: 'Direct Purchase Center', speciality: 'Samba & Kuruvai Paddy' },
      { nameEn: 'Pattukkottai Coconut Wholesale Mandi', nameTa: 'பட்டுக்கோட்டை தென்னை மொத்த சந்தை', type: 'Coconut Terminal', speciality: 'Raw Coconut, Tender & Copra' },
    ],
    specialtyEn: 'Rice Bowl of Tamil Nadu (தென்னகத்தின் நெற்களஞ்சியம்) powered by ancient Kallanai (Grand Anicut).',
    specialtyTa: 'தமிழகத்தின் நெற்களஞ்சியம், கரிகாலன் கட்டிய கல்லணை பாசனம் மற்றும் பட்டுக்கோட்டை தென்னை வளம்.',
    netCroppedAreaHa: 268000,
  },
  {
    id: 'theni',
    en: 'Theni',
    ta: 'தேனி',
    capitalEn: 'Theni',
    capitalTa: 'தேனி',
    zoneEn: 'Southern Cumbum Valley & Western Ghats',
    zoneTa: 'கம்பம் பள்ளத்தாக்கு & தென் மேற்கு தொடர்ச்சி மலை',
    coordinates: { lat: 10.0104, lng: 77.4768 },
    mainAreas: [
      { en: 'Cumbum', ta: 'கம்பம்', type: 'Taluk', specialty: 'Cumbum Panneer Thratchai (GI Grapes 365 days a year)' },
      { en: 'Bodinayakanur', ta: 'போடிநாயக்கனூர்', type: 'Taluk', specialty: 'Cardamom City of India (ஏலக்காய் நகரம்)' },
      { en: 'Periyakulam', ta: 'பெரியகுளம்', type: 'Taluk', specialty: 'Mango orchards, TNAU Horticultural College & Banana' },
      { en: 'Uthamapalayam', ta: 'உத்தமபாளையம்', type: 'Taluk', specialty: 'Periyar riverbed Paddy, Coconut & Betel vine' },
      { en: 'Andipatti', ta: 'ஆண்டிபட்டி', type: 'Taluk', specialty: 'Vaigai Dam ayacut, Cotton & Millets' },
      { en: 'Chinnamanur', ta: 'சின்னமனூர்', type: 'Taluk', specialty: 'Banana wholesale market & Paddy' },
    ],
    majorCrops: [
      { en: 'Cumbum Panneer Grapes (GI)', ta: 'கம்பம் பன்னீர் திராட்சை (GI)' },
      { en: 'Cardamom (Small Cardamom)', ta: 'ஏலக்காய்' },
      { en: 'Mango (Vadipatti/Periyakulam)', ta: 'மாம்பழம்' },
      { en: 'Banana (Grand Naine, Red Banana)', ta: 'செவ்வாழை & ஜி-9 வாழை' },
      { en: 'Coffee & Pepper', ta: 'காபி & மிளகு' },
      { en: 'Cotton', ta: 'பருத்தி' },
    ],
    soilTypes: [
      { en: 'Rich Valley Alluvium', ta: 'பள்ளத்தாக்கு வண்டல் மண்' },
      { en: 'Red Sandy Loam', ta: 'செம்மண்' },
      { en: 'Hill Forest Loam', ta: 'மலைக் காடு மண்' },
    ],
    annualRainfallMm: 852,
    waterBasinEn: 'Mullaperiyar & Vaigai River Valley (Suruliyar, Shanmuganathi)',
    waterBasinTa: 'முல்லைப்பெரியாறு & வைகை (சுருளியாறு, சண்முகநதி)',
    keyMandis: [
      { nameEn: 'Bodinayakanur Cardamom Auction Center', nameTa: 'போடிநாயக்கனூர் ஏலக்காய் ஏல மையம்', type: 'National Spice Terminal', speciality: 'Small Cardamom (India’s highest turnover)' },
      { nameEn: 'Cumbum Valley Grape Wholesale Market', nameTa: 'கம்பம் திராட்சை மொத்த சந்தை', type: 'Specialized Fruit Mandi', speciality: 'Muscat / Panneer Grapes' },
    ],
    specialtyEn: 'Year-round Cumbum Panneer Grapes (GI), Bodinayakanur Cardamom capital, and Periyar irrigation paradise.',
    specialtyTa: 'வருடம் முழுவதும் விளையும் கம்பம் பன்னீர் திராட்சை (GI), போடி ஏலக்காய் மற்றும் பெரியாறு பாசன வளம்.',
    netCroppedAreaHa: 118000,
  },
  {
    id: 'thoothukudi',
    en: 'Thoothukudi',
    ta: 'தூத்துக்குடி',
    capitalEn: 'Thoothukudi',
    capitalTa: 'தூத்துக்குடி',
    zoneEn: 'Southern Dry & Coastal Saline Zone',
    zoneTa: 'தென் வறண்ட & கடற்கரை மண்டலம்',
    coordinates: { lat: 8.7642, lng: 78.1348 },
    mainAreas: [
      { en: 'Kovilpatti', ta: 'கோவில்பட்டி', type: 'Taluk', specialty: 'Kovilpatti Kadalai Mittai GI, Cotton & Maize' },
      { en: 'Srivaikuntam', ta: 'ஸ்ரீவைகுண்டம்', type: 'Taluk', specialty: 'Tamirabarani river paddy & Nendran banana' },
      { en: 'Tiruchendur', ta: 'திருச்செந்தூர்', type: 'Taluk', specialty: 'Coastal Coconut, Betel vine & Palmyra' },
      { en: 'Vilathikulam', ta: 'விளாத்திகுளம்', type: 'Taluk', specialty: 'Dryland Red Chilli, Blackgram & Cotton' },
      { en: 'Ottapidaram', ta: 'ஒட்டப்பிடாரம்', type: 'Taluk', specialty: 'Black soil Cotton, Millets & Pulses' },
      { en: 'Sathankulam', ta: 'சாத்தான்குளம்', type: 'Taluk', specialty: 'Groundnut, Cashew & Palmyra jaggery' },
      { en: 'Eral', ta: 'ஏரல்', type: 'Taluk', specialty: 'Tamirabarani delta Banana & Paddy' },
      { en: 'Kayathar', ta: 'கயத்தாறு', type: 'Taluk', specialty: 'Millets, Windmills & Sunflower' },
    ],
    majorCrops: [
      { en: 'Rainfed Cotton', ta: 'மானாவாரி பருத்தி' },
      { en: 'Dryland Red Chilli', ta: 'மிளகாய்' },
      { en: 'Blackgram & Greengram', ta: 'உளுந்து & பாசிப்பயறு' },
      { en: 'Tamirabarani Paddy', ta: 'தாமிரபரணி நெல்' },
      { en: 'Nendran Banana', ta: 'நேந்திரன் வாழை' },
      { en: 'Groundnut', ta: 'நிலக்கடலை' },
    ],
    soilTypes: [
      { en: 'Deep Black Cotton Soil', ta: 'ஆழ்ந்த கரிசல் மண்' },
      { en: 'Tamirabarani Alluvium', ta: 'தாமிரபரணி வண்டல்' },
      { en: 'Coastal Sandy Loam', ta: 'கடற்கரை மணல்' },
    ],
    annualRainfallMm: 660,
    waterBasinEn: 'Tamirabarani Lower Basin & Srivaikuntam Anicut',
    waterBasinTa: 'தாமிரபரணி கடைமடை & ஸ்ரீவைகுண்டம் அணைக்கட்டு',
    keyMandis: [
      { nameEn: 'Kovilpatti Cotton & Grain Mandi', nameTa: 'கோவில்பட்டி பருத்தி & தானிய அங்காடி', type: 'Regulated Market', speciality: 'Cotton, Maize & Groundnut' },
      { nameEn: 'Vilathikulam Chilli Market', nameTa: 'விளாத்திகுளம் மிளகாய் சந்தை', type: 'Spice Mandi', speciality: 'Mundu Chilli & Pulses' },
    ],
    specialtyEn: 'Deep black soils of Kovilpatti cotton belt, Kovilpatti Kadalai Mittai (GI), and Tamirabarani banana groves.',
    specialtyTa: 'கோவில்பட்டி கரிசல் நில பருத்தி, புவிசார் குறியீடு பெற்ற கடலை மிட்டாய் மற்றும் தாமிரபரணி வாழை.',
    netCroppedAreaHa: 182000,
  },
  {
    id: 'tiruchirappalli',
    en: 'Tiruchirappalli',
    ta: 'திருச்சிராப்பள்ளி',
    capitalEn: 'Tiruchirappalli',
    capitalTa: 'திருச்சிராப்பள்ளி',
    zoneEn: 'Cauvery Central Basin',
    zoneTa: 'காவிரி மத்திய படுகை மண்டலம்',
    coordinates: { lat: 10.7905, lng: 78.7047 },
    mainAreas: [
      { en: 'Manachanallur', ta: 'மண்ணச்சநல்லூர்', type: 'Taluk', specialty: 'Tamil Nadu’s Rice Mill Capital (பொன்னி அரிசி மையம்)' },
      { en: 'Lalgudi', ta: 'லால்குடி', type: 'Taluk', specialty: 'Cauvery & Coleroon fertile Paddy, Sugarcane & Banana' },
      { en: 'Thottiyam', ta: 'தொட்டியம்', type: 'Taluk', specialty: 'Banana capital & NRCB research interface' },
      { en: 'Musiri', ta: 'முசிறி', type: 'Taluk', specialty: 'Riverbank Banana, Betel vine & Sugarcane' },
      { en: 'Srirangam', ta: 'ஸ்ரீரங்கம்', type: 'Taluk', specialty: 'Island agriculture, Floriculture & Lotus ponds' },
      { en: 'Manapparai', ta: 'மணப்பாறை', type: 'Taluk', specialty: 'Famous Manapparai Cattle Market & Murukku hub' },
      { en: 'Thuraiyur', ta: 'துரையூர்', type: 'Taluk', specialty: 'Small Onion, Tapioca & Maize' },
      { en: 'Marungapuri', ta: 'மருங்காபுரி', type: 'Taluk', specialty: 'Dryland Millets & Pulses' },
    ],
    majorCrops: [
      { en: 'Banana (NRCB Headquarters)', ta: 'வாழை (தேசிய வாழை ஆராய்ச்சி மையம்)' },
      { en: 'Paddy (Manachanallur Ponni)', ta: 'மண்ணச்சநல்லூர் பொன்னி நெல்' },
      { en: 'Sugarcane', ta: 'கரும்பு' },
      { en: 'Small Onion', ta: 'சின்ன வெங்காயம்' },
      { en: 'Maize & Millets', ta: 'மக்காச்சோளம் & சிறுதானியங்கள்' },
    ],
    soilTypes: [
      { en: 'Cauvery River Alluvium', ta: 'காவிரி ஆற்று வண்டல்' },
      { en: 'Red Sandy Loam', ta: 'செம்மண்' },
      { en: 'Clay Loam', ta: 'களிமண் வண்டல்' },
    ],
    annualRainfallMm: 818,
    waterBasinEn: 'Cauvery River, Coleroon & Upper Anicut (Mukkombu)',
    waterBasinTa: 'காவிரி, கொள்ளிடம் & முக்கொம்பு மேலணை',
    keyMandis: [
      { nameEn: 'Manachanallur Modern Rice Mills Cluster', nameTa: 'மண்ணச்சநல்லூர் நவீன அரிசி ஆலைகள் முனையம்', type: 'State Rice Terminal', speciality: 'Deluxe Ponni Rice' },
      { nameEn: 'Gandhi Market Trichy', nameTa: 'திருச்சி காந்தி மார்க்கெட்', type: 'Central Perishable Mandi', speciality: 'Vegetables, Fruits, Banana' },
    ],
    specialtyEn: 'National Research Centre for Banana (NRCB), Manachanallur Ponni rice mills, and Mukkombu dam bifurcation.',
    specialtyTa: 'தேசிய வாழை ஆராய்ச்சி மையம் (NRCB), மண்ணச்சநல்லூர் பொன்னி அரிசி மற்றும் முக்கொம்பு பாசனப் பெருமை.',
    netCroppedAreaHa: 169000,
  },
  {
    id: 'tirunelveli',
    en: 'Tirunelveli',
    ta: 'திருநெல்வேலி',
    capitalEn: 'Tirunelveli',
    capitalTa: 'திருநெல்வேலி',
    zoneEn: 'Tamirabarani River Basin / Southern Zone',
    zoneTa: 'தாமிரபரணி படுகை / தென் மண்டலம்',
    coordinates: { lat: 8.7139, lng: 77.7567 },
    mainAreas: [
      { en: 'Ambasamudram', ta: 'அம்பாசமுத்திரம்', type: 'Taluk', specialty: 'Tamirabarani headwaters, Paddy & TRRI Rice varieties' },
      { en: 'Cheranmahadevi', ta: 'சேரன்மகாதேவி', type: 'Taluk', specialty: 'Canal irrigated Paddy, Banana & Coconut' },
      { en: 'Nanguneri', ta: 'நாங்குநேரி', type: 'Taluk', specialty: 'Rainfed Black soil Cotton, Pulses & Groundnut' },
      { en: 'Radhapuram', ta: 'ராதாபுரம்', type: 'Taluk', specialty: 'Palmyra trees, Coconut groves & Wind agrivoltaics' },
      { en: 'Palayamkottai', ta: 'பாளையம்ங்கோட்டை', type: 'Taluk', specialty: 'Vegetables & Floriculture' },
      { en: 'Manur', ta: 'மானூர்', type: 'Taluk', specialty: 'Manur Big Tank ayacut, Cotton & Millets' },
      { en: 'Tisayanvilai', ta: 'திசையன்விளை', type: 'Taluk', specialty: 'Red soil (தேரி நிலம்) Cashew, Drumstick & Palmyra' },
    ],
    majorCrops: [
      { en: 'Kar & Samba Paddy', ta: 'கார் & சம்பா நெல்' },
      { en: 'Banana (Poovan, Rasthali)', ta: 'வாழை' },
      { en: 'Coconut', ta: 'தென்னை' },
      { en: 'Palmyra Jaggery (கருப்பட்டி)', ta: 'பனை கருப்பட்டி' },
      { en: 'Cotton', ta: 'பருத்தி' },
      { en: 'Mango', ta: 'மாம்பழம்' },
    ],
    soilTypes: [
      { en: 'Perennial River Alluvium', ta: 'ஜீவநதி தாமிரபரணி வண்டல்' },
      { en: 'Red Teri Soil', ta: 'செந்தேரி மண்' },
      { en: 'Black Cotton Soil', ta: 'கரிசல் மண்' },
    ],
    annualRainfallMm: 814,
    waterBasinEn: 'Tamirabarani River (Only perennial river in TN), Manimuthar & Servalar Dams',
    waterBasinTa: 'ஜீவநதி தாமிரபரணி, மணிமுத்தாறு & சேர்வலாறு அணை',
    keyMandis: [
      { nameEn: 'Nainarkulam Vegetable Market', nameTa: 'நைனார்குளம் காய்கறி அங்காடி', type: 'Wholesale Mandi', speciality: 'Vegetables & Greens' },
      { nameEn: 'Ambasamudram Paddy Market', nameTa: 'அம்பாசமுத்திரம் நெல் சந்தை', type: 'Regulated Market', speciality: 'Kar Paddy & Samba Rice' },
    ],
    specialtyEn: 'Blessed by Tamirabarani—the only perennial river of Tamil Nadu—yielding 3 paddy crops annually.',
    specialtyTa: 'தமிழகத்தின் ஒரே வற்றாத ஜீவநதி தாமிரபரணி பாசனம் மூலம் ஆண்டுக்கு மூன்று போகம் நெல் விளையும் பூமி.',
    netCroppedAreaHa: 131000,
  },
  {
    id: 'tirupathur',
    en: 'Tirupathur',
    ta: 'திருப்பத்தூர்',
    capitalEn: 'Tirupathur',
    capitalTa: 'திருப்பத்தூர்',
    zoneEn: 'North Western / Northern Hills',
    zoneTa: 'வடமேற்கு / வடமலை மண்டலம்',
    coordinates: { lat: 12.4926, lng: 78.5667 },
    mainAreas: [
      { en: 'Tirupathur', ta: 'திருப்பத்தூர்', type: 'Taluk', specialty: 'Paddy, Groundnut & Sugarcane' },
      { en: 'Vaniyambadi', ta: 'வாணியம்பாடி', type: 'Taluk', specialty: 'Palar riverbed Coconut & Vegetables' },
      { en: 'Ambur', ta: 'ஆம்பூர்', type: 'Taluk', specialty: 'Horticulture, Floriculture & Dairy' },
      { en: 'Natrampalli', ta: 'நாட்ராம்பள்ளி', type: 'Taluk', specialty: 'Sugarcane Jaggery & Coconut wholesale' },
      { en: 'Yelagiri Hills', ta: 'ஏலகிரி மலை', type: 'Taluk', specialty: 'Jackfruit, Guava, Honey & Organic Spices' },
      { en: 'Jolarpet', ta: 'ஜோலார்பேட்டை', type: 'Taluk', specialty: 'Mango orchards & Dairy' },
    ],
    majorCrops: [
      { en: 'Mango', ta: 'மாம்பழம்' },
      { en: 'Coconut', ta: 'தென்னை' },
      { en: 'Groundnut', ta: 'நிலக்கடலை' },
      { en: 'Sugarcane & Jaggery', ta: 'கரும்பு & வெல்லம்' },
      { en: 'Yelagiri Jackfruit & Spices', ta: 'ஏலகிரி பலா & மசாலா' },
    ],
    soilTypes: [
      { en: 'Red Sandy Loam', ta: 'செம்மண்' },
      { en: 'Hill Rocky Loam', ta: 'மலை சரளை மண்' },
      { en: 'Palar Alluvium', ta: 'பாலாற்று வண்டல்' },
    ],
    annualRainfallMm: 988,
    waterBasinEn: 'Palar River Basin & Yelagiri streams',
    waterBasinTa: 'பாலாறு & ஏலகிரி நீரோடைகள்',
    keyMandis: [
      { nameEn: 'Natrampalli Jaggery Market', nameTa: 'நாட்ராம்பள்ளி வெல்லம் அங்காடி', type: 'Specialized Mandi', speciality: 'Cane Jaggery & Coconut' },
      { nameEn: 'Vaniyambadi Regulated Market', nameTa: 'வாணியம்பாடி ஒழுங்குமுறை விற்பனைக்கூடம்', type: 'Regulated Market', speciality: 'Groundnut & Grain' },
    ],
    specialtyEn: 'Natrampalli country jaggery and Yelagiri Hills cool-climate jackfruit, honey, and organic produce.',
    specialtyTa: 'நாட்ராம்பள்ளி நாட்டு வெல்லம் தயாரிப்பு மற்றும் ஏலகிரி மலை இயற்கை பலா, தேன் விளைச்சல்.',
    netCroppedAreaHa: 89000,
  },
  {
    id: 'tiruppur',
    en: 'Tiruppur',
    ta: 'திருப்பூர்',
    capitalEn: 'Tiruppur',
    capitalTa: 'திருப்பூர்',
    zoneEn: 'Western Agro-Climatic Zone',
    zoneTa: 'மேற்கு வேளாண் மண்டலம்',
    coordinates: { lat: 11.1085, lng: 77.3411 },
    mainAreas: [
      { en: 'Kangeyam', ta: 'காங்கேயம்', type: 'Taluk', specialty: 'Copra Capital of India, Coconut Oil & Kangeyam Bull breed' },
      { en: 'Dharapuram', ta: 'தாராபுரம்', type: 'Taluk', specialty: 'Amaravathi Basin Paddy, Red Chilli & Maize' },
      { en: 'Udumalaipettai', ta: 'உடுமலைப்பேட்டை', type: 'Taluk', specialty: 'Thirumoorthy Dam ayacut, Maize, Poultry & Vegetables' },
      { en: 'Uthukuli', ta: 'ஊத்துக்குளி', type: 'Taluk', specialty: 'GI Tag Uthukuli Butter (வெண்ணெய்), Milk & Millets' },
      { en: 'Madathukulam', ta: 'மடத்துக்குளம்', type: 'Taluk', specialty: 'Sugarcane, Paper Mills & Paddy' },
      { en: 'Palladam', ta: 'பல்லடம்', type: 'Taluk', specialty: 'Broiler Poultry capital & Maize trade' },
      { en: 'Avinashi', ta: 'அவிநாசி', type: 'Taluk', specialty: 'Banana, Vegetables & Coconut' },
    ],
    majorCrops: [
      { en: 'Coconut & Copra', ta: 'தென்னை & கொப்பரை (காங்கேயம்)' },
      { en: 'Maize (Corn)', ta: 'மக்காச்சோளம்' },
      { en: 'Cotton', ta: 'பருத்தி' },
      { en: 'Dairy & Butter (Uthukuli GI)', ta: 'ஊத்துக்குளி வெண்ணெய் & பால்' },
      { en: 'Sugarcane', ta: 'கரும்பு' },
      { en: 'Red Chilli (Dharapuram)', ta: 'தாராபுரம் மிளகாய்' },
    ],
    soilTypes: [
      { en: 'Red Gravelly Loam', ta: 'செம்மண் சரளை' },
      { en: 'Black Cotton Soil', ta: 'கரிசல் மண்' },
      { en: 'Calcareous Loam', ta: 'சுண்ணாம்பு கலந்த மண்' },
    ],
    annualRainfallMm: 605,
    waterBasinEn: 'Amaravathi River, PAP Canal & Noyyal',
    waterBasinTa: 'அமராவதி நதி, பரம்பிக்குளம் ஆழியாறு & நொய்யல்',
    keyMandis: [
      { nameEn: 'Kangeyam Copra Wholesale Mandi', nameTa: 'காங்கேயம் கொப்பரை மொத்த அங்காடி', type: 'National Oilseeds Mandi', speciality: 'Copra, Coconut Oil & Cake' },
      { nameEn: 'Udumalaipettai Maize Market', nameTa: 'உடுமலைப்பேட்டை மக்காச்சோள சந்தை', type: 'Feed Grain Terminal', speciality: 'Poultry Feed Maize' },
    ],
    specialtyEn: 'Kangeyam Copra trading hub, legendary Kangeyam cattle breed, and GI-certified Uthukuli butter.',
    specialtyTa: 'நாட்டின் முதன்மை காங்கேயம் கொப்பரை தேங்காய் எண்ணெய் மண்டி, காங்கேயம் காளை மற்றும் ஊத்துக்குளி வெண்ணெய்.',
    netCroppedAreaHa: 188000,
  },
  {
    id: 'tiruvallur',
    en: 'Tiruvallur',
    ta: 'திருவள்ளூர்',
    capitalEn: 'Tiruvallur',
    capitalTa: 'திருவள்ளூர்',
    zoneEn: 'North Eastern Coastal Zone',
    zoneTa: 'வடகிழக்கு கடலோர மண்டலம்',
    coordinates: { lat: 13.1432, lng: 79.9083 },
    mainAreas: [
      { en: 'Ponneri', ta: 'பொன்னேரி', type: 'Taluk', specialty: 'Ponneri Paddy & Freshwater Shrimp farming' },
      { en: 'Gummidipoondi', ta: 'கும்மிடிப்பூண்டி', type: 'Taluk', specialty: 'Watermelon, Groundnut & Cashew' },
      { en: 'Tiruttani', ta: 'திருத்தணி', type: 'Taluk', specialty: 'Sugarcane, Jaggery & Mango' },
      { en: 'Uthukottai', ta: 'ஊத்துக்கோட்டை', type: 'Taluk', specialty: 'Kandaleru-Poondi canal, Paddy & Vegetables' },
      { en: 'Poonamallee', ta: 'பூந்தமல்லி', type: 'Taluk', specialty: 'Jasmine, Betel vine & Chennai fresh greens supply' },
      { en: 'Pallipattu', ta: 'பள்ளிப்பட்டு', type: 'Taluk', specialty: 'Kusasthalai river sugarcane & Paddy' },
      { en: 'Avadi', ta: 'ஆவடி', type: 'Taluk', specialty: 'Peri-urban horticulture & Dairy' },
      { en: 'RK Pet', ta: 'ஆர்.கே.பேட்டை', type: 'Taluk', specialty: 'Millets, Mango & Groundnut' },
    ],
    majorCrops: [
      { en: 'Paddy', ta: 'நெல்' },
      { en: 'Watermelon', ta: 'தர்பூசணி' },
      { en: 'Sugarcane', ta: 'கரும்பு' },
      { en: 'Groundnut', ta: 'நிலக்கடலை' },
      { en: 'Green Vegetables & Flowers', ta: 'கீரைகள், காய்கறி & பூக்கள்' },
    ],
    soilTypes: [
      { en: 'Coastal Alluvium', ta: 'கடற்கரை வண்டல்' },
      { en: 'Red Sandy Loam', ta: 'செம்மண்' },
      { en: 'Clayey Loam', ta: 'களிமண் வண்டல்' },
    ],
    annualRainfallMm: 1184,
    waterBasinEn: 'Kosasthalaiyar, Araniyar & Poondi Reservoir',
    waterBasinTa: 'கொசஸ்தலையாறு, ஆரணியாறு & பூண்டி நீர்த்தேக்கம்',
    keyMandis: [
      { nameEn: 'Ponneri Regulated Market', nameTa: 'பொன்னேரி ஒழுங்குமுறை விற்பனைக்கூடம்', type: 'Regulated Market', speciality: 'Paddy & Watermelon' },
      { nameEn: 'Tiruvallur Vegetable Market', nameTa: 'திருவள்ளூர் காய்கறி அங்காடி', type: 'Wholesale Mandi', speciality: 'Daily Greens & Vegetables' },
    ],
    specialtyEn: 'Primary fruit, watermelon and fresh vegetable lifeline to Chennai metropolis; Poondi reservoir ayacut.',
    specialtyTa: 'சென்னை பெருநகரத்தின் முதன்மை காய்கறி, கீரை, தர்பூசணி உற்பத்தி மற்றும் பூண்டி ஏரி பாசனம்.',
    netCroppedAreaHa: 136000,
  },
  {
    id: 'tiruvannamalai',
    en: 'Tiruvannamalai',
    ta: 'திருவண்ணாமலை',
    capitalEn: 'Tiruvannamalai',
    capitalTa: 'திருவண்ணாமலை',
    zoneEn: 'North Eastern Zone & Jawadhu Hills',
    zoneTa: 'வடகிழக்கு மண்டலம் & ஜவ்வாது மலை',
    coordinates: { lat: 12.2253, lng: 79.0747 },
    mainAreas: [
      { en: 'Arni', ta: 'ஆரணி', type: 'Taluk', specialty: 'Arni Silk & GI Arni Ponni Rice Mills Capital' },
      { en: 'Polur', ta: 'போளூர்', type: 'Taluk', specialty: 'Paddy, Groundnut & Sugarcane' },
      { en: 'Cheyyar', ta: 'செய்யாறு', type: 'Taluk', specialty: 'Cheyyar River basin Paddy, Cotton & Groundnut' },
      { en: 'Vandavasi', ta: 'வந்தவாசி', type: 'Taluk', specialty: 'Paddy, Sugarcane & Watermelon' },
      { en: 'Jawadhu Hills (Jamunamarathur)', ta: 'ஜவ்வாது மலை', type: 'Taluk', specialty: 'Tribal Organic Little Millet (சாமை), Jackfruit & Honey' },
      { en: 'Chengam', ta: 'செங்கம்', type: 'Taluk', specialty: 'Sathanur Dam ayacut, Maize & Millets' },
      { en: 'Kalasapakkam', ta: 'கலசப்பாக்கம்', type: 'Taluk', specialty: 'Paddy & Groundnut' },
      { en: 'Thandarampattu', ta: 'தண்டராம்பட்டு', type: 'Taluk', specialty: 'Sathanur Left Bank canal Paddy & Fish' },
    ],
    majorCrops: [
      { en: 'Paddy (Arni Ponni)', ta: 'ஆரணி பொன்னி நெல்' },
      { en: 'Groundnut', ta: 'நிலக்கடலை' },
      { en: 'Sugarcane', ta: 'கரும்பு' },
      { en: 'Samai / Little Millet', ta: 'ஜவ்வாது மலை சாமை' },
      { en: 'Cotton', ta: 'பருத்தி' },
      { en: 'Jackfruit', ta: 'பலாப்பழம்' },
    ],
    soilTypes: [
      { en: 'Red Sandy Loam', ta: 'செம்மண்' },
      { en: 'Black Loam', ta: 'கரிசல் மண்' },
      { en: 'Hill Tribal Organic Soil', ta: 'மலை அங்கக மண்' },
    ],
    annualRainfallMm: 1046,
    waterBasinEn: 'Thenpennai River (Sathanur Dam) & Cheyyar River',
    waterBasinTa: 'தென்பெண்ணை (சாத்தனூர் அணை) & செய்யாறு',
    keyMandis: [
      { nameEn: 'Arni Rice Wholesale Mandi', nameTa: 'ஆரணி அரிசி மொத்த அங்காடி', type: 'State Rice Terminal', speciality: 'Arni Ponni Rice' },
      { nameEn: 'Cheyyar Regulated Market', nameTa: 'செய்யாறு ஒழுங்குமுறை விற்பனைக்கூடம்', type: 'Regulated Market', speciality: 'Groundnut & Paddy' },
    ],
    specialtyEn: 'Famous Arni Ponni Rice milling belt, massive Sathanur Dam irrigation, and Jawadhu tribal millets.',
    specialtyTa: 'சுவைமிக்க ஆரணி பொன்னி அரிசி, சாத்தனூர் அணை பிரம்மாண்ட பாசனம் மற்றும் ஜவ்வாது மலை சாமை.',
    netCroppedAreaHa: 232000,
  },
  {
    id: 'tiruvarur',
    en: 'Tiruvarur',
    ta: 'திருவாரூர்',
    capitalEn: 'Tiruvarur',
    capitalTa: 'திருவாரூர்',
    zoneEn: 'Cauvery Delta Heartland',
    zoneTa: 'காவிரி டெல்டா மையம்',
    coordinates: { lat: 10.7725, lng: 79.6365 },
    mainAreas: [
      { en: 'Mannargudi', ta: 'மன்னார்குடி', type: 'Taluk', specialty: 'Haridra Nadhi, Samba Paddy & Modern Rice Mill clusters' },
      { en: 'Thiruthuraipoondi', ta: 'திருத்துறைப்பூண்டி', type: 'Taluk', specialty: 'Traditional Heirloom Paddy Capital (மாப்பிள்ளை சம்பா, கருப்பு கவுனி)' },
      { en: 'Kudavasal', ta: 'குடவாசல்', type: 'Taluk', specialty: 'Kuruvai Paddy & Blackgram' },
      { en: 'Valangaiman', ta: 'வலங்கைமான்', type: 'Taluk', specialty: 'Paddy, Sugarcane & Banana' },
      { en: 'Needamangalam', ta: 'நீடாமங்கலம்', type: 'Taluk', specialty: 'Vennar bifurcations & TNAU Krishi Vigyan Kendra' },
      { en: 'Nannilam', ta: 'நன்னிலம்', type: 'Taluk', specialty: 'Mudikondan river Paddy & Pulses' },
      { en: 'Muthupet', ta: 'முத்துப்பேட்டை', type: 'Taluk', specialty: 'Mangrove eco-basin, Coastal Coconut & Marine aqua' },
      { en: 'Koothanallur', ta: 'கூத்தநல்லூர்', type: 'Taluk', specialty: 'Paddy & Dairy' },
    ],
    majorCrops: [
      { en: 'Samba & Thaladi Paddy', ta: 'சம்பா & தாளடி நெல்' },
      { en: 'Traditional Rice Varieties', ta: 'பாரம்பரிய நெல் ரகங்கள் (கருப்பு கவுனி)' },
      { en: 'Blackgram & Greengram', ta: 'உளுந்து & பயறு' },
      { en: 'Cotton', ta: 'பருத்தி' },
      { en: 'Sesame', ta: 'எள்' },
      { en: 'Coconut', ta: 'தென்னை' },
    ],
    soilTypes: [
      { en: 'Deep Delta Alluvial Clay', ta: 'ஆழ்ந்த டெல்டா வண்டல் களிமண்' },
      { en: 'River Silt', ta: 'ஆற்று வண்டல்' },
      { en: 'Coastal Loam', ta: 'கடற்கரை வண்டல்' },
    ],
    annualRainfallMm: 1260,
    waterBasinEn: 'Vennar, Pamaniyar, Koraiyar & Mulliyar (Cauvery Delta)',
    waterBasinTa: 'வெண்ணாறு, பாமணியாறு, கோரையாறு & முள்ளியாறு',
    keyMandis: [
      { nameEn: 'Mannargudi Regulated Market', nameTa: 'மன்னார்குடி ஒழுங்குமுறை விற்பனைக்கூடம்', type: 'Regulated Market', speciality: 'Samba Paddy & Pulses' },
      { nameEn: 'Thiruthuraipoondi Traditional Rice Mandi', nameTa: 'திருத்துறைப்பூண்டி பாரம்பரிய நெல் சந்தை', type: 'Heritage Grain Terminal', speciality: 'Heirloom & Organic Rice' },
    ],
    specialtyEn: 'Birthplace of traditional rice revival (Nel Jayaraman movement) and core delta paddy granary.',
    specialtyTa: 'நெல் ஜெயராமன் முன்னெடுத்த பாரம்பரிய நெல் திருவிழா பூமி மற்றும் காவிரி டெல்டாவின் இதயப் பகுதி.',
    netCroppedAreaHa: 172000,
  },
  {
    id: 'vellore',
    en: 'Vellore',
    ta: 'வேலூர்',
    capitalEn: 'Vellore',
    capitalTa: 'வேலூர்',
    zoneEn: 'North Eastern Zone',
    zoneTa: 'வடகிழக்கு வேளாண் மண்டலம்',
    coordinates: { lat: 12.9165, lng: 79.1325 },
    mainAreas: [
      { en: 'Katpadi', ta: 'காட்பாடி', type: 'Taluk', specialty: 'Paddy, Groundnut & Vegetables' },
      { en: 'Gudiyatham', ta: 'குடியாத்தம்', type: 'Taluk', specialty: 'Banana, Gudiyatham Jaggery, Match works & Mango' },
      { en: 'Anaicut', ta: 'அணைக்கட்டு', type: 'Taluk', specialty: 'Paddy, Sugarcane & Dairy' },
      { en: 'KV Kuppam', ta: 'கே.வி.குப்பம்', type: 'Taluk', specialty: 'Groundnut, Pulses & Mulberry silk' },
      { en: 'Pernambut', ta: 'பேரணாம்பட்டு', type: 'Taluk', specialty: 'Vegetables & Floriculture' },
      { en: 'Vellore Rural', ta: 'வேலூர் புறநகர்', type: 'Taluk', specialty: 'Horticulture & Dairy farming' },
    ],
    majorCrops: [
      { en: 'Paddy', ta: 'நெல்' },
      { en: 'Banana', ta: 'வாழை' },
      { en: 'Groundnut', ta: 'நிலக்கடலை' },
      { en: 'Sugarcane', ta: 'கரும்பு' },
      { en: 'Mango', ta: 'மாம்பழம்' },
      { en: 'Mulberry (Silk)', ta: 'பட்டுப்புழு மல்பெரி' },
    ],
    soilTypes: [
      { en: 'Red Sandy Loam', ta: 'செம்மண்' },
      { en: 'Palar River Alluvium', ta: 'பாலாற்று வண்டல்' },
    ],
    annualRainfallMm: 1018,
    waterBasinEn: 'Palar River & Koundinya Wildlife riverlets',
    waterBasinTa: 'பாலாறு & கவுண்டின்யா நதிப் படுகை',
    keyMandis: [
      { nameEn: 'Gudiyatham Banana & Jaggery Market', nameTa: 'குடியாத்தம் வாழை & வெல்லம் அங்காடி', type: 'Specialized Mandi', speciality: 'Banana Bunches & Cane Jaggery' },
      { nameEn: 'Katpadi Regulated Market', nameTa: 'காட்பாடி ஒழுங்குமுறை விற்பனைக்கூடம்', type: 'Regulated Market', speciality: 'Paddy & Groundnut' },
    ],
    specialtyEn: 'Famous for Gudiyatham cane jaggery, rich Palar alluvium, and sericulture silk clusters.',
    specialtyTa: 'குடியாத்தம் கரும்பு வெல்லம், பாலாற்று படுகை விவசாயம் மற்றும் மல்பெரி பட்டுப்புழு வளர்ப்பு.',
    netCroppedAreaHa: 68000,
  },
  {
    id: 'villupuram',
    en: 'Villupuram',
    ta: 'விழுப்புரம்',
    capitalEn: 'Villupuram',
    capitalTa: 'விழுப்புரம்',
    zoneEn: 'North Eastern Agro Zone',
    zoneTa: 'வடகிழக்கு வேளாண் மண்டலம்',
    coordinates: { lat: 11.9401, lng: 79.4861 },
    mainAreas: [
      { en: 'Tindivanam', ta: 'திண்டிவனம்', type: 'Taluk', specialty: 'Groundnut & Cashew Capital of Northern TN' },
      { en: 'Gingee (Senji)', ta: 'செஞ்சி', type: 'Taluk', specialty: 'Paddy, Sugarcane, Millets & Gingee Fort hill eco-farming' },
      { en: 'Vikravandi', ta: 'விக்கிரவாண்டி', type: 'Taluk', specialty: 'Sugarcane, Modern Sugar mills & Paddy' },
      { en: 'Vanur', ta: 'வானூர்', type: 'Taluk', specialty: 'Cashew, Watermelon & Coastal farming' },
      { en: 'Marakkanam', ta: 'மரக்காணம்', type: 'Taluk', specialty: 'Salt pans, Shrimp aquaculture & Coconut' },
      { en: 'Kandachipuram', ta: 'கண்டாச்சிபுரம்', type: 'Taluk', specialty: 'Thenpennai basin Paddy & Maize' },
      { en: 'Thiruvennainallur', ta: 'திருவெண்ணெய்நல்லூர்', type: 'Taluk', specialty: 'Sugarcane, Banana & Paddy' },
    ],
    majorCrops: [
      { en: 'Groundnut', ta: 'நிலக்கடலை (திண்டிவனம்)' },
      { en: 'Sugarcane', ta: 'கரும்பு' },
      { en: 'Paddy', ta: 'நெல்' },
      { en: 'Watermelon', ta: 'தர்பூசணி' },
      { en: 'Tapioca', ta: 'மரவள்ளிக்கிழங்கு' },
      { en: 'Cashew', ta: 'முந்திரி' },
    ],
    soilTypes: [
      { en: 'Red Sandy Loam', ta: 'செம்மண்' },
      { en: 'Clay Loam', ta: 'களிமண் வண்டல்' },
      { en: 'Coastal Sand', ta: 'கடற்கரை மணல்' },
    ],
    annualRainfallMm: 1060,
    waterBasinEn: 'Thenpennai & Varahanadhi River Basin',
    waterBasinTa: 'தென்பெண்ணை & வராகநதி பாசனம்',
    keyMandis: [
      { nameEn: 'Tindivanam Groundnut & Cashew Market', nameTa: 'திண்டிவனம் கடலை & முந்திரி சந்தை', type: 'National Oilseeds Mandi', speciality: 'Groundnut Pods, Kernels & Oil' },
      { nameEn: 'Gingee Regulated Market', nameTa: 'செஞ்சி ஒழுங்குமுறை விற்பனைக்கூடம்', type: 'Regulated Market', speciality: 'Paddy, Millets & Pulses' },
    ],
    specialtyEn: 'Tindivanam premier groundnut trading center in South India and major sugar production factories.',
    specialtyTa: 'தென்னிந்தியாவின் முதன்மை திண்டிவனம் நிலக்கடலை அங்காடி மற்றும் முன்னணி சர்க்கரை ஆலைகள்.',
    netCroppedAreaHa: 210000,
  },
  {
    id: 'virudhunagar',
    en: 'Virudhunagar',
    ta: 'விருதுநகர்',
    capitalEn: 'Virudhunagar',
    capitalTa: 'விருதுநகர்',
    zoneEn: 'Southern Semi-Arid Zone',
    zoneTa: 'தென் வறண்ட பகுதி',
    coordinates: { lat: 9.5680, lng: 77.9624 },
    mainAreas: [
      { en: 'Rajapalayam', ta: 'ராஜபாளையம்', type: 'Taluk', specialty: 'Cotton spinning hub, Rajapalayam Mango & Western Ghats spices' },
      { en: 'Sattur', ta: 'சாத்தூர்', type: 'Taluk', specialty: 'Dryland Red Chilli, Blackgram & Cucumber' },
      { en: 'Srivilliputhur', ta: 'ஸ்ரீவில்லிபுத்தூர்', type: 'Taluk', specialty: 'GI Srivilliputhur Palkova (Dairy), Sugarcane & Paddy' },
      { en: 'Aruppukkottai', ta: 'அருப்புக்கோட்டை', type: 'Taluk', specialty: 'Rainfed Cotton, Maize & Millets' },
      { en: 'Sivakasi', ta: 'சிவகாசி', type: 'Taluk', specialty: 'Dryland Millets, Cotton & Fireworks logistics' },
      { en: 'Kariapatti', ta: 'காரியாபட்டி', type: 'Taluk', specialty: 'Black soil Cotton, Pulses & Groundnut' },
      { en: 'Watrap', ta: 'வத்திராயிருப்பு', type: 'Taluk', specialty: 'Pilavakkal Dam ayacut Paddy & Coconut' },
      { en: 'Tiruchuli', ta: 'திருச்சுழி', type: 'Taluk', specialty: 'Gundar river basin Paddy & Millets' },
    ],
    majorCrops: [
      { en: 'Cotton', ta: 'பருத்தி (ராஜபாளையம்)' },
      { en: 'Dryland Chilli', ta: 'மிளகாய் (சாத்தூர்)' },
      { en: 'Dairy & Srivilliputhur Palkova (GI)', ta: 'ஸ்ரீவில்லிபுத்தூர் பால்கோவா (GI)' },
      { en: 'Maize & Millets', ta: 'மக்காச்சோளம் & கம்பு' },
      { en: 'Blackgram', ta: 'உளுந்து' },
      { en: 'Groundnut', ta: 'நிலக்கடலை' },
    ],
    soilTypes: [
      { en: 'Deep Black Cotton Soil', ta: 'ஆழ்ந்த கரிசல் மண்' },
      { en: 'Red Sandy Loam', ta: 'செம்மண்' },
      { en: 'Calcareous Clay', ta: 'சுண்ணாம்பு களிமண்' },
    ],
    annualRainfallMm: 730,
    waterBasinEn: 'Gundar, Vaippar & Pilavakkal Dam',
    waterBasinTa: 'குண்டாறு, வைப்பாறு & பிலவக்கல் அணை',
    keyMandis: [
      { nameEn: 'Virudhunagar Oilseeds & Cotton Market', nameTa: 'விருதுநகர் எண்ணெய் வித்துக்கள் & பருத்தி சந்தை', type: 'Commodity Exchange', speciality: 'Edible Oils, Cotton & Grain' },
      { nameEn: 'Sattur Chilli Mandi', nameTa: 'சாத்தூர் மிளகாய் அங்காடி', type: 'Spice Mandi', speciality: 'Dry Red Chillies' },
    ],
    specialtyEn: 'Benchmark trading market for edible oils and cotton in South India; GI-certified Srivilliputhur Palkova.',
    specialtyTa: 'தென்னிந்திய சமையல் எண்ணெய் மற்றும் பருத்தி விலை நிர்ணய சந்தை, ஸ்ரீவில்லிபுத்தூர் பால்கோவா (GI).',
    netCroppedAreaHa: 156000,
  },
];

// Simple lookup list for dropdown selects across the entire app
export const TN_38_DISTRICTS_LIST = TN_38_DISTRICTS.map((d) => ({
  en: d.en,
  ta: d.ta,
  capitalEn: d.capitalEn,
  capitalTa: d.capitalTa,
  zoneEn: d.zoneEn,
  zoneTa: d.zoneTa,
}));

// Quick helpers
export function getAllDistricts(): DistrictDetail[] {
  return TN_38_DISTRICTS;
}

export function getDistrictByEn(name: string): DistrictDetail | undefined {
  if (!name) return undefined;
  const clean = name.toLowerCase().trim();
  return TN_38_DISTRICTS.find(
    (d) => d.en.toLowerCase() === clean || clean.includes(d.en.toLowerCase())
  );
}

export function searchDistricts(searchTerm: string): DistrictDetail[] {
  if (!searchTerm.trim()) return TN_38_DISTRICTS;
  const q = searchTerm.toLowerCase().trim();
  return TN_38_DISTRICTS.filter((d) => {
    return (
      d.en.toLowerCase().includes(q) ||
      d.ta.includes(q) ||
      d.capitalEn.toLowerCase().includes(q) ||
      d.capitalTa.includes(q) ||
      d.zoneEn.toLowerCase().includes(q) ||
      d.zoneTa.includes(q) ||
      d.waterBasinEn.toLowerCase().includes(q) ||
      d.waterBasinTa.includes(q) ||
      d.mainAreas.some(
        (a) => a.en.toLowerCase().includes(q) || a.ta.includes(q) || a.specialty?.toLowerCase().includes(q)
      ) ||
      d.majorCrops.some((c) => c.en.toLowerCase().includes(q) || c.ta.includes(q)) ||
      d.soilTypes.some((s) => s.en.toLowerCase().includes(q) || s.ta.includes(q))
    );
  });
}
