import { MarketPrice, WeatherData } from '../types';

export const DEMO_WEATHER: WeatherData = {
  district: 'Thanjavur',
  village: 'Thiruvaiyaru',
  tempC: 31,
  humidityPct: 76,
  rainProbabilityPct: 45,
  windSpeedKmh: 14,
  conditionEn: 'Partly Cloudy with Humid Breeze',
  conditionTa: 'பகுதி மேகமூட்டம் & மிதமான ஈரக்காற்று',
  updatedAt: 'Today, 08:30 AM',
  forecast: [
    {
      date: 'Today',
      dayEn: 'Mon',
      dayTa: 'திங்கள்',
      maxTemp: 32,
      minTemp: 24,
      rainProb: 35,
      conditionEn: 'Scattered Clouds',
      conditionTa: 'சிதறிய மேகங்கள்',
      agriculturalAdviceEn: 'Favorable for nursery maintenance and field inspection.',
      agriculturalAdviceTa: 'நாற்றங்கால் பராமரிப்பு மற்றும் வயல் பார்வைக்கு உகந்த நாள்.',
    },
    {
      date: 'Tomorrow',
      dayEn: 'Tue',
      dayTa: 'செவ்வாய்',
      maxTemp: 30,
      minTemp: 23,
      rainProb: 65,
      conditionEn: 'Afternoon Showers',
      conditionTa: 'மதிய வேளையில் மழை',
      agriculturalAdviceEn: 'Postpone fertilizer top-dressing and irrigation.',
      agriculturalAdviceTa: 'மேலுரம் இடுவதையும் தண்ணீர் பாய்ச்சுவதையும் தவிர்க்கவும்.',
    },
    {
      date: 'Day 3',
      dayEn: 'Wed',
      dayTa: 'புதன்',
      maxTemp: 29,
      minTemp: 22,
      rainProb: 55,
      conditionEn: 'Light Thunderstorms',
      conditionTa: 'லேசான இடிமழை',
      agriculturalAdviceEn: 'Ensure clear drainage channels to avert waterlogging.',
      agriculturalAdviceTa: 'வயல் வடிகால் வாய்க்கால்களை தூர்வாரி தயார் நிலையில் வைக்கவும்.',
    },
    {
      date: 'Day 4',
      dayEn: 'Thu',
      dayTa: 'வியாழன்',
      maxTemp: 32,
      minTemp: 24,
      rainProb: 20,
      conditionEn: 'Clear Sky',
      conditionTa: 'தெளிவான வானம்',
      agriculturalAdviceEn: 'Optimal for neem spray and pest trap installation.',
      agriculturalAdviceTa: 'வேப்பெண்ணெய் கரைசல் தெளிக்க மற்றும் பூச்சி பொறி வைக்க ஏற்ற நாள்.',
    },
    {
      date: 'Day 5',
      dayEn: 'Fri',
      dayTa: 'வெள்ளி',
      maxTemp: 33,
      minTemp: 25,
      rainProb: 15,
      conditionEn: 'Sunny & Warm',
      conditionTa: 'வெயில் & இதமான வெப்பம்',
      agriculturalAdviceEn: 'Good window for intercultural weeding and mechanical hoeing.',
      agriculturalAdviceTa: 'களை எடுக்கும் பணிக்கு மிகவும் உகந்த நாள்.',
    },
  ],
};

export const DEMO_MARKET_PRICES: MarketPrice[] = [
  {
    cropEn: 'Paddy (Grade A / பொன்னி)',
    cropTa: 'நெல் (சன்ன ரகம் / பொன்னி)',
    mandiEn: 'Thanjavur Regulated Market',
    mandiTa: 'தஞ்சாவூர் ஒழுங்குமுறை விற்பனைக்கூடம்',
    district: 'Thanjavur',
    modalPrice: 2380,
    minPrice: 2250,
    maxPrice: 2460,
    changePct: +2.8,
    unit: '₹ / Quintal',
    date: 'Today',
    trend: [
      { date: 'Mon', price: 2300 },
      { date: 'Tue', price: 2320 },
      { date: 'Wed', price: 2315 },
      { date: 'Thu', price: 2350 },
      { date: 'Fri', price: 2360 },
      { date: 'Sat', price: 2370 },
      { date: 'Today', price: 2380 },
    ],
  },
  {
    cropEn: 'Tomato (நாட்டு / ஹைபிரிட்)',
    cropTa: 'தக்காளி (நாட்டு & கலப்பின ரகம்)',
    mandiEn: 'Oddanchatram Central Market',
    mandiTa: 'ஒட்டன்சத்திரம் மத்திய காய்கறி சந்தை',
    district: 'Dindigul',
    modalPrice: 1550,
    minPrice: 1300,
    maxPrice: 1750,
    changePct: +5.4,
    unit: '₹ / Quintal',
    date: 'Today',
    trend: [
      { date: 'Mon', price: 1350 },
      { date: 'Tue', price: 1400 },
      { date: 'Wed', price: 1420 },
      { date: 'Thu', price: 1480 },
      { date: 'Fri', price: 1510 },
      { date: 'Sat', price: 1530 },
      { date: 'Today', price: 1550 },
    ],
  },
  {
    cropEn: 'Banana (Poovan / பூவன்)',
    cropTa: 'வாழை (பூவன் பழம்)',
    mandiEn: 'Tiruchirappalli Gandhi Market',
    mandiTa: 'திருச்சிராப்பள்ளி காந்தி சந்தை',
    district: 'Tiruchirappalli',
    modalPrice: 2200,
    minPrice: 1900,
    maxPrice: 2450,
    changePct: -1.2,
    unit: '₹ / Quintal',
    date: 'Today',
    trend: [
      { date: 'Mon', price: 2280 },
      { date: 'Tue', price: 2260 },
      { date: 'Wed', price: 2250 },
      { date: 'Thu', price: 2220 },
      { date: 'Fri', price: 2210 },
      { date: 'Sat', price: 2200 },
      { date: 'Today', price: 2200 },
    ],
  },
  {
    cropEn: 'Groundnut Pods (மணிலா)',
    cropTa: 'நிலக்கடலை காய் (மணிலா)',
    mandiEn: 'Tindivanam Regulated Market',
    mandiTa: 'திண்டிவனம் ஒழுங்குமுறை விற்பனைக்கூடம்',
    district: 'Villupuram',
    modalPrice: 6900,
    minPrice: 6400,
    maxPrice: 7250,
    changePct: +1.8,
    unit: '₹ / Quintal',
    date: 'Today',
    trend: [
      { date: 'Mon', price: 6750 },
      { date: 'Tue', price: 6780 },
      { date: 'Wed', price: 6810 },
      { date: 'Thu', price: 6850 },
      { date: 'Fri', price: 6880 },
      { date: 'Sat', price: 6890 },
      { date: 'Today', price: 6900 },
    ],
  },
  {
    cropEn: 'Blackgram (உளுந்து)',
    cropTa: 'உளுந்து (கருப்பு உளுந்து)',
    mandiEn: 'Cuddalore Regulated Market',
    mandiTa: 'கடலூர் ஒழுங்குமுறை விற்பனைக்கூடம்',
    district: 'Cuddalore',
    modalPrice: 8350,
    minPrice: 7900,
    maxPrice: 8700,
    changePct: +0.6,
    unit: '₹ / Quintal',
    date: 'Today',
    trend: [
      { date: 'Mon', price: 8250 },
      { date: 'Tue', price: 8280 },
      { date: 'Wed', price: 8300 },
      { date: 'Thu', price: 8310 },
      { date: 'Fri', price: 8320 },
      { date: 'Sat', price: 8340 },
      { date: 'Today', price: 8350 },
    ],
  },
];
